'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

type Mode='paper'|'testnet'|'live';
type Signal={above:boolean,line:number|null,close:number|null,atr:number|null,previous?:{above:boolean,line:number|null,close:number|null}};
type LeveragePlan={valid:boolean;reason:string;distancePct?:number;baseLeverage?:number;hardStop?:number;hardStopDistancePct?:number;riskLeverage?:number;finalLeverage?:number;riskPct?:number};
type Row={rank:number,symbol:string,change:number,price:number,quoteVolume:number,signals:Record<string,Signal|null>,directionQualified:boolean,eligible:boolean,reason:string,leveragePlan:LeveragePlan};
type Stats={engineStartedAt:string;runningSince:string|null;runningSeconds:number;scans:number;rankingRefreshes:number;retries:number;dataErrors:number;entries:number;exits:number;wins:number;losses:number;winRate:number;realizedPnl:number;unrealizedPnl:number;hardStopMoves:number};
type Snapshot={connected:boolean,running:boolean,mode:Mode,lastTick:string|null,lastRankingUpdate:string|null,nextRankingUpdate:string|null,account:{equity:number|null,available:number|null}|null,position:{symbol:string;qty:number;entryPrice:number;markPrice:number;unrealizedPnl:number;hardStop:number|null;rank:number|null;leverage?:number;distancePct?:number;hardStopDistancePct?:number;initialRiskPct?:number}|null,ranking:Row[],logs:Array<{at:string,level:string,message:string}>,config:{maxRiskPct:number;rankingSize:number;rankingRefreshSec:number;hardStopAtr:number;hardStopStepAtr:number;cooldownBars:number},stats:Stats,marketStream:{status:'disconnected'|'connecting'|'connected'|'reconnecting'|'degraded';lastMessage:string|null;reconnects:number},error:string|null};
const EMPTY_STATS:Stats={engineStartedAt:new Date(0).toISOString(),runningSince:null,runningSeconds:0,scans:0,rankingRefreshes:0,retries:0,dataErrors:0,entries:0,exits:0,wins:0,losses:0,winRate:0,realizedPnl:0,unrealizedPnl:0,hardStopMoves:0};
const EMPTY:Snapshot={connected:false,running:false,mode:'paper',lastTick:null,lastRankingUpdate:null,nextRankingUpdate:null,account:null,position:null,ranking:[],logs:[],config:{maxRiskPct:10,rankingSize:10,rankingRefreshSec:60,hardStopAtr:1,hardStopStepAtr:.5,cooldownBars:3},stats:EMPTY_STATS,marketStream:{status:'disconnected',lastMessage:null,reconnects:0},error:null};
const API='http://localhost:3001/api';
const periods=[['15m','15分钟'],['1h','1小时'],['4h','4小时'],['1d','1日']];
const num=(v:number|null,d=2)=>v==null?'—':v.toLocaleString('en-US',{maximumFractionDigits:d});
const time=(v:string|null)=>v?new Date(v).toLocaleTimeString('zh-CN',{hour12:false}):'—';
const duration=(seconds:number)=>{const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=Math.floor(seconds%60);return h?`${h}小时 ${m}分`:m?`${m}分 ${s}秒`:`${s}秒`};
const judgement=(r:Row,targetRank:number|null)=>{if(!r.directionQualified||!r.eligible)return{label:r.reason,signal:false};const sig=r.signals['5m'];if(!sig?.above)return{label:'等待5m站上趋势线',signal:false};if(r.rank!==targetRank)return{label:'候补 · 等待首位目标失效',signal:false};if(!r.leveragePlan.valid)return{label:`首位目标 · 空仓等待 ${r.leveragePlan.reason}`,signal:false};return{label:`首位目标合格 · ${r.leveragePlan.finalLeverage}倍`,signal:true}};

export default function Home(){
 const[s,setS]=useState<Snapshot>(EMPTY),[mode,setMode]=useState<Mode>('paper'),[apiKey,setApiKey]=useState(''),[secret,setSecret]=useState(''),[unlock,setUnlock]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState('');
 const[params,setParams]=useState(EMPTY.config);
 const initialized=useRef(false);
 const call=async(path:string,body?:unknown)=>{setBusy(path);setNotice('');try{const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body??{})});const data=await r.json();if(!r.ok)throw new Error(data.error||'操作失败');if(data.snapshot){setS(data.snapshot);setMode(data.snapshot.mode);setParams(data.snapshot.config)}setNotice(data.message||'已完成')}catch(e){setNotice(e instanceof Error?e.message:'操作失败')}finally{setBusy('')}};
 useEffect(()=>{const poll=async()=>{try{const r=await fetch(`${API}/snapshot`);if(r.ok){const d=await r.json();setS(d);if(!initialized.current){initialized.current=true;setMode(d.mode);setParams(d.config)}}}catch{}};poll();const id=setInterval(poll,1000);return()=>clearInterval(id)},[]);
 const active=useMemo(()=>s.ranking.filter(r=>r.directionQualified).length,[s.ranking]);
 const targetRank=useMemo(()=>s.ranking.find(r=>r.eligible&&r.signals['5m']?.above)?.rank??null,[s.ranking]);
 const watchlist=useMemo(()=>s.ranking.flatMap(r=>{const sig=r.signals['5m'];if(!r.eligible||!sig||sig.above||sig.line==null||sig.close==null||!sig.atr||!r.price)return[];const rawGap=sig.line-r.price,gap=Math.max(0,rawGap);return[{...r,gapPrice:rawGap,gapPct:rawGap/r.price*100,gapAtr:gap/sig.atr,trigger:sig.line}]}).sort((a,b)=>a.gapAtr-b.gapAtr||a.rank-b.rank).slice(0,5),[s.ranking]);
 const connect=()=>call('/connect',{mode,apiKey:apiKey.trim(),secretKey:secret.trim(),liveUnlock:unlock});
 const save=()=>call('/config',params);
 return <main>
  <header><div className="brand"><span>ST</span><div><b>Trend Executor</b><small>BINANCE 自动交易系统</small></div></div><div className="health"><i className={s.running?'pulse':''}/>{s.running?'策略运行中':s.connected?'已连接 · 未启动':'尚未连接'}</div></header>
  <div className="shell">
   <section className="hero"><div><p className="eyebrow">LOCAL CONTROL CENTER</p><h1>趋势执行，<em>规则优先。</em></h1><p>涨幅榜前10 · 五周期全部在线上入场 · 动态软硬止损</p></div><div className="mode-card"><span>当前环境</span><strong>{s.mode==='paper'?'纸面交易':s.mode==='testnet'?'测试网':'实盘'}</strong><small>{s.running?'引擎正在自动执行':'引擎处于安全停止状态'}</small></div></section>
   {notice&&<div className={`notice ${notice.includes('失败')||notice.includes('错误')?'bad':''}`}>{notice}</div>}
   <div className="grid">
    <section className="card connect"><div className="card-title"><div><p>01 · 连接</p><h2>账户与运行环境</h2></div><span className={s.connected?'ok':''}>{s.connected?'已连接':'未连接'}</span></div>
     <label>运行模式<select value={mode} onChange={e=>setMode(e.target.value as Mode)}><option value="paper">纸面交易（推荐）</option><option value="testnet">Binance 测试网</option><option value="live">Binance 实盘</option></select></label>
     {mode!=='paper'&&<><label>API Key<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="仅保存在本地后端内存" autoComplete="off"/></label><label>Secret Key<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="关闭服务后自动清除" autoComplete="off"/></label></>}
     {mode==='live'&&<label>实盘解锁短语<input value={unlock} onChange={e=>setUnlock(e.target.value)} placeholder="输入：我确认实盘风险" autoComplete="off"/></label>}
     <button className="primary" disabled={!!busy} onClick={connect}>{busy==='/connect'?'正在验证…':mode==='paper'?'启用纸面账户':'验证并连接'}</button><p className="hint">密钥不写入磁盘、浏览器存储或日志。建议API仅开启合约交易权限并绑定本机IP，禁止提现权限。</p>
    </section>
    <section className="card params"><div className="card-title"><div><p>02 · 参数</p><h2>策略配置</h2></div><span>ST 10 / 3</span></div>
     <div className="param-grid"><label>理论风险上限<input type="number" min="1" max="10" step=".5" value={params.maxRiskPct} onChange={e=>setParams({...params,maxRiskPct:+e.target.value})}/><small>% 权益</small></label><label>榜单数量<input type="number" min="1" max="20" value={params.rankingSize} onChange={e=>setParams({...params,rankingSize:+e.target.value})}/><small>名</small></label><label>榜单刷新<input type="number" min="15" max="300" value={params.rankingRefreshSec} onChange={e=>setParams({...params,rankingRefreshSec:+e.target.value})}/><small>秒</small></label><label>冷却K线<input type="number" min="0" max="20" value={params.cooldownBars} onChange={e=>setParams({...params,cooldownBars:+e.target.value})}/><small>根 5m</small></label><label>硬止损缓冲<input type="number" min=".5" max="3" step=".1" value={params.hardStopAtr} onChange={e=>setParams({...params,hardStopAtr:+e.target.value})}/><small>ATR</small></label><label>上移阈值<input type="number" min=".1" max="2" step=".1" value={params.hardStopStepAtr} onChange={e=>setParams({...params,hardStopStepAtr:+e.target.value})}/><small>ATR</small></label></div>
     <button className="secondary" disabled={!!busy||s.running} onClick={save}>保存参数</button><p className="hint">动态敞口：距离&lt;2%为5倍，2–2.5%为4倍，2.5–5%为2倍，5–10%为1倍；再按硬止损风险向下降档。</p>
    </section>
    <section className="card control"><div className="card-title"><div><p>03 · 执行</p><h2>策略控制</h2></div><span className={s.running?'running':''}>{s.running?'AUTO':'SAFE'}</span></div>
     <div className="account"><div><span>账户权益</span><b>{num(s.account?.equity??null)} <small>USDT</small></b></div><div><span>可用余额</span><b>{num(s.account?.available??null)} <small>USDT</small></b></div></div>
     <div className="actions"><button className="start" disabled={!s.connected||s.running||!!busy} onClick={()=>call('/start')}>启动自动交易</button><button disabled={!s.running||!!busy} onClick={()=>call('/stop')}>停止新开仓</button><button className="danger" disabled={!s.position||!!busy} onClick={()=>confirm('确认市价平掉全部仓位？')&&call('/panic',{confirm:'CLOSE_ALL'})}>紧急平仓</button></div><p className="hint">“停止”不会主动平掉已有仓位，已有仓位仍保留交易所硬止损；“紧急平仓”会撤保护单并市价退出。</p>
    </section>
   </div>

   <section className="stats card"><div className="card-title"><div><p>TEST OBSERVATORY</p><h2>测试运行统计</h2></div><span className={s.running?'running':''}>{s.running?'记录中':'已暂停'}</span></div><div className="stats-grid"><article className="featured"><span>策略运行时长</span><b>{duration(s.stats?.runningSeconds||0)}</b><small>{s.running?'测试数据持续累计':'启动策略后开始计时'}</small></article><article><span>入场 / 平仓</span><b>{s.stats?.entries||0} <small>/ {s.stats?.exits||0}</small></b><small>成功建立与退出的仓位</small></article><article><span>胜率</span><b>{num(s.stats?.winRate||0,1)}<small>%</small></b><small>{s.stats?.wins||0} 胜 · {s.stats?.losses||0} 负</small></article><article><span>估算已实现盈亏</span><b className={(s.stats?.realizedPnl||0)>=0?'green':'red'}>{num(s.stats?.realizedPnl||0)} <small>USDT</small></b><small>暂未扣除手续费与资金费</small></article><article><span>未实现盈亏</span><b className={(s.stats?.unrealizedPnl||0)>=0?'green':'red'}>{num(s.stats?.unrealizedPnl||0)} <small>USDT</small></b><small>当前仓位实时估算</small></article><article><span>5m 入场扫描</span><b>{s.stats?.scans||0}</b><small>已完成K线触发的检查次数</small></article><article><span>榜单更新</span><b>{s.stats?.rankingRefreshes||0}</b><small>成功刷新涨幅榜次数</small></article><article><span>止损上移</span><b>{s.stats?.hardStopMoves||0}</b><small>动态保护价调整次数</small></article><article className={(s.stats?.dataErrors||0)>0?'warning':''}><span>数据异常 / 重试</span><b>{s.stats?.dataErrors||0} <small>/ {s.stats?.retries||0}</small></b><small>指标失败与网络重试次数</small></article></div><footer className="stats-note">统计从本次交易引擎启动后开始累计；测试网盈亏按成交均价估算，最终结果请以 Binance 测试网账户账单为准。</footer></section>

   <section className="watch card"><div className="card-title"><div><p>BREAKOUT WATCH</p><h2>重点观察 · 即将突破</h2></div><span>{watchlist.length} 个候选</span></div>{watchlist.length?<div className="watch-grid">{watchlist.map((r,i)=><article key={r.symbol} className={i===0?'nearest':''}><div className="watch-head"><span>榜单 #{r.rank}</span><b>{i===0?'距离最近':'等待突破'}</b></div><h3>{r.symbol.replace('USDT','')}<small>/USDT</small></h3><div className="watch-prices"><div><span>当前价格</span><strong>{num(r.price,6)}</strong></div><div><span>5m Up Trend线</span><strong>{num(r.trigger,6)}</strong></div></div><div className={`watch-amplitude ${r.gapPct<=0?'crossed':''}`}><span>实时距离幅度</span><b>{r.gapPct>0?`需上涨 ${r.gapPct.toFixed(2)}%`:`盘中已高于线 ${Math.abs(r.gapPct).toFixed(2)}%`}</b></div><div className="distance"><span><i style={{width:`${Math.max(8,100-Math.min(100,r.gapAtr*50))}%`}}/></span><b>{r.gapPct>0?`还差 ${r.gapAtr.toFixed(2)} ATR`:'等待5m收盘确认'}</b></div><p>已完成5m收盘 {num(r.signals['5m']?.close??null,6)} · 当前价差 {num(Math.abs(r.gapPrice),6)}</p></article>)}</div>:<div className="empty">当前没有“高周期全部合格且5分钟仍在线下”的币种。列表会随每次榜单更新自动变化。</div>}<footer className="watch-note">观察条件：15m、1h、4h、1d全部在线上，最后一根已完成5m仍在线下；幅度按WebSocket约1秒推送的当前价格计算。盘中越线仍需等待5m收盘确认后才允许入场。</footer></section>

   <section className="position card"><div className="card-title"><div><p>LIVE POSITION</p><h2>当前持仓</h2></div><span>{s.position?'持仓中':'空仓'}</span></div>{s.position?<div className="position-grid"><div><span>合约</span><b>{s.position.symbol}</b></div><div><span>动态杠杆</span><b>{s.position.leverage?`${s.position.leverage}×`:'—'}</b></div><div><span>5m收盘→趋势线跌幅</span><b>{s.position.distancePct!=null?`${s.position.distancePct.toFixed(2)}%`:'—'}</b></div><div><span>5m收盘→硬止损跌幅</span><b>{s.position.hardStopDistancePct!=null?`${s.position.hardStopDistancePct.toFixed(2)}%`:'—'}</b></div><div><span>杠杆后理论风险</span><b>{s.position.initialRiskPct!=null?`${s.position.initialRiskPct.toFixed(2)}%`:'—'}</b></div><div><span>数量</span><b>{num(s.position.qty,6)}</b></div><div><span>入场均价</span><b>{num(s.position.entryPrice,6)}</b></div><div><span>标记价格</span><b>{num(s.position.markPrice,6)}</b></div><div><span>未实现盈亏</span><b className={s.position.unrealizedPnl>=0?'green':'red'}>{num(s.position.unrealizedPnl)} USDT</b></div><div><span>硬止损</span><b>{num(s.position.hardStop,6)}</b></div></div>:<div className="empty">暂无持仓。系统只锁定五周期全部在线上的最高排名币；若它风险不合格则保持空仓等待，不会交易后面的币。</div>}</section>

   <section className="ranking card"><div className="card-title"><div><p>MARKET SCANNER</p><h2>涨幅榜前 {params.rankingSize}</h2></div><div className="scan-meta"><span>{active} 个高周期合格</span><span>{time(s.lastRankingUpdate)} 榜单更新 · 价格约1秒推送</span></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>合约</th><th>最新价</th><th>24H</th><th>成交额</th>{periods.map(p=><th key={p[0]}>{p[1]}</th>)}<th>5m状态</th><th>① 实时价→趋势线</th><th>② 5m收盘→趋势线</th><th>③ 5m收盘→硬止损 / 风险</th><th>判断</th></tr></thead><tbody>{s.ranking.length?s.ranking.map(r=>{const line=r.signals['5m']?.line??null,distance=line&&r.price?(r.price-line)/r.price*100:null,status=judgement(r,targetRank),plan=r.leveragePlan;return <tr key={r.symbol}><td className="rank">{String(r.rank).padStart(2,'0')}</td><td><b>{r.symbol.replace('USDT','')}</b><small>/USDT</small></td><td>{num(r.price,6)}</td><td><span className="gain">+{r.change.toFixed(2)}%</span></td><td>{num(r.quoteVolume/1e6,1)}M</td>{periods.map(p=><td key={p[0]}><span className={`sig ${r.signals[p[0]]?.above?'up':'down'}`}>{r.signals[p[0]]?.above?'上方':'下方'}</span></td>)}<td><span className={`sig ${r.signals['5m']?.above?'up':'down'}`}>{r.signals['5m']?.above?'上方':'下方'}</span></td><td>{r.directionQualified&&distance!=null?<span className={`line-distance ${distance>=0?'above':'below'}`}>{distance>=0?`向下 ${distance.toFixed(2)}%`:`需上涨 ${Math.abs(distance).toFixed(2)}%`}</span>:<span className="muted">—</span>}</td><td>{r.directionQualified&&plan.distancePct!=null?<span className={`line-distance ${plan.distancePct>=0?'above':'below'}`}>{plan.distancePct>=0?`向下 ${plan.distancePct.toFixed(2)}% · 基础 ${plan.baseLeverage}×`:`需上涨 ${Math.abs(plan.distancePct).toFixed(2)}%`}</span>:<span className="muted">—</span>}</td><td>{r.directionQualified&&plan.distancePct!=null&&plan.distancePct>=0?<span className={`leverage-plan ${plan.valid?'valid':'invalid'}`}>{plan.valid?`向下 ${plan.hardStopDistancePct?.toFixed(2)}% · 最终 ${plan.finalLeverage}× · 账户风险 ${plan.riskPct?.toFixed(2)}%`:`向下 ${plan.hardStopDistancePct?.toFixed(2)}% · ${plan.reason}`}</span>:<span className="muted">等待5m站上线</span>}</td><td><span className={status.signal?'entry-signal':r.rank===targetRank?'eligible':'muted'}>{status.label}</span></td></tr>}):<tr><td colSpan={14}><div className="empty">连接并启动后加载实时榜单</div></td></tr>}</tbody></table></div></section>

   <section className="logs card"><div className="card-title"><div><p>SYSTEM EVENTS</p><h2>运行日志</h2></div><span>最近 {s.logs.length} 条</span></div><div className="log-list">{s.logs.length?s.logs.map((l,i)=><div key={`${l.at}-${i}`}><time>{time(l.at)}</time><span className={l.level}>{l.level.toUpperCase()}</span><p>{l.message}</p></div>):<div className="empty">暂无事件</div>}</div></section>
  </div>
 </main>
}
