'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

type Channel='paper'|'live';
type Signal={above:boolean,line:number|null,close:number|null,atr:number|null,previous?:{above:boolean,line:number|null,close:number|null}};
type LeveragePlan={valid:boolean;reason:string;referencePrice?:number;distancePct?:number;liveLineDistancePct?:number;hardStop?:number;hardStopDistancePct?:number;riskLeverage?:number;finalLeverage?:number;riskPct?:number};
type Row={rank:number,symbol:string,change:number,price:number,quoteVolume:number,signals:Record<string,Signal|null>,directionQualified:boolean,eligible:boolean,reason:string,leveragePlan:LeveragePlan};
type Stats={engineStartedAt:string;runningSince:string|null;runningSeconds:number;scans:number;rankingRefreshes:number;retries:number;marginRetries:number;dataErrors:number;entries:number;exits:number;wins:number;losses:number;winRate:number;realizedPnl:number;unrealizedPnl:number;hardStopMoves:number;rotations:number};
type Config={maxRiskPct:number;maxTrendDropPct:number;marginReservePct:number;rankingSize:number;rankingRefreshSec:number;hardStopAtr:number;hardStopStepAtr:number;cooldownBars:number};
type Position={symbol:string;qty:number;entryPrice:number;markPrice:number;unrealizedPnl:number;hardStop:number|null;rank:number|null;leverage?:number;distancePct?:number;liveLineDistancePct?:number;hardStopDistancePct?:number;initialRiskPct?:number};
type Snapshot={connected:boolean;running:boolean;mode:Channel;lockedMode?:Channel|null;lastTick:string|null;lastRankingUpdate:string|null;nextRankingUpdate:string|null;account:{equity:number|null;available:number|null}|null;position:Position|null;ranking:Row[];logs:Array<{at:string;level:string;message:string}>;config:Config;stats:Stats;marketStream:{status:'disconnected'|'connecting'|'connected'|'reconnecting'|'degraded';lastMessage:string|null;reconnects:number};error:string|null};
type LiveAuth={configured:boolean;authenticated:boolean;expiresAt:string|null};

const EMPTY_STATS:Stats={engineStartedAt:new Date(0).toISOString(),runningSince:null,runningSeconds:0,scans:0,rankingRefreshes:0,retries:0,marginRetries:0,dataErrors:0,entries:0,exits:0,wins:0,losses:0,winRate:0,realizedPnl:0,unrealizedPnl:0,hardStopMoves:0,rotations:0};
const DEFAULT_CONFIG:Config={maxRiskPct:20,maxTrendDropPct:10,marginReservePct:2,rankingSize:10,rankingRefreshSec:60,hardStopAtr:1,hardStopStepAtr:.5,cooldownBars:3};
const empty=(mode:Channel):Snapshot=>({connected:false,running:false,mode,lockedMode:mode,lastTick:null,lastRankingUpdate:null,nextRankingUpdate:null,account:null,position:null,ranking:[],logs:[],config:{...DEFAULT_CONFIG},stats:{...EMPTY_STATS},marketStream:{status:'disconnected',lastMessage:null,reconnects:0},error:null});
const periods=[['15m','15分钟'],['1h','1小时'],['4h','4小时'],['1d','1日']];
const num=(v:number|null,d=2)=>v==null?'—':v.toLocaleString('en-US',{maximumFractionDigits:d});
const time=(v:string|null)=>v?new Date(v).toLocaleTimeString('zh-CN',{hour12:false}):'—';
const duration=(seconds:number)=>{const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=Math.floor(seconds%60);return h?`${h}小时 ${m}分`:m?`${m}分 ${s}秒`:`${s}秒`};
const judgement=(r:Row,targetRank:number|null,position:Position|null)=>{if(position?.symbol===r.symbol)return{label:'当前持仓 · 监控更高排名目标',signal:true};if(!r.directionQualified||!r.eligible)return{label:r.reason,signal:false};const sig=r.signals['5m'];if(!sig?.above)return{label:'等待5m站上趋势线',signal:false};if(r.rank!==targetRank)return{label:'候补 · 等待首位目标失效',signal:false};const isHigher=position?.rank!=null&&r.rank<position.rank;if(!r.leveragePlan.valid)return{label:`${isHigher?'更高排名目标':'首位目标'} · 等待 ${r.leveragePlan.reason}`,signal:false};if(position&&position.rank!=null&&!isHigher)return{label:'首位目标合格 · 排名未高于当前持仓',signal:false};return{label:`${isHigher?'更高排名换仓目标':'首位目标合格'} · ${r.leveragePlan.finalLeverage}倍`,signal:true}};

function PositionView({channel,s}:{channel:Channel;s:Snapshot}){return <section className={`position card channel-position ${channel}`}><div className="card-title"><div><p>{channel==='paper'?'PAPER POSITION':'LIVE POSITION'}</p><h2>{channel==='paper'?'纸面持仓':'实盘持仓'}</h2></div><span className={s.position?'running':''}>{s.position?'持仓中':'空仓'}</span></div>{s.position?<div className="position-grid"><div><span>合约</span><b>{s.position.symbol}</b></div><div><span>动态杠杆</span><b>{s.position.leverage?`${s.position.leverage}×`:'—'}</b></div><div><span>入场实时价→趋势线</span><b>{s.position.liveLineDistancePct!=null?`${s.position.liveLineDistancePct.toFixed(2)}%`:'—'}</b></div><div><span>趋势线理论账户风险</span><b>{s.position.initialRiskPct!=null?`${s.position.initialRiskPct.toFixed(2)}%`:'—'}</b></div><div><span>数量</span><b>{num(s.position.qty,6)}</b></div><div><span>入场均价</span><b>{num(s.position.entryPrice,6)}</b></div><div><span>标记价格</span><b>{num(s.position.markPrice,6)}</b></div><div><span>未实现盈亏</span><b className={s.position.unrealizedPnl>=0?'green':'red'}>{num(s.position.unrealizedPnl)} USDT</b></div><div><span>硬止损</span><b>{num(s.position.hardStop,6)}</b></div></div>:<div className="empty">{s.connected?'当前空仓，两套通道会独立选择和管理仓位。':'尚未连接此通道。'}</div>}</section>}

function StatsView({channel,s}:{channel:Channel;s:Snapshot}){return <section className="stats card"><div className="card-title"><div><p>{channel==='paper'?'PAPER OBSERVATORY':'LIVE OBSERVATORY'}</p><h2>{channel==='paper'?'纸面运行统计':'实盘运行统计'}</h2></div><span className={s.running?'running':''}>{s.running?'独立记录中':'已暂停'}</span></div><div className="stats-grid"><article className="featured"><span>策略运行时长</span><b>{duration(s.stats.runningSeconds||0)}</b><small>{s.running?'当前通道持续累计':'启动后开始计时'}</small></article><article><span>入场 / 平仓</span><b>{s.stats.entries||0} <small>/ {s.stats.exits||0}</small></b><small>当前通道独立统计</small></article><article><span>自动换仓</span><b>{s.stats.rotations||0}</b><small>更高排名合格目标替换次数</small></article><article><span>保证金缩量重试</span><b>{s.stats.marginRetries||0}</b><small>仅统计交易所明确拒绝的安全重试</small></article><article><span>胜率</span><b>{num(s.stats.winRate||0,1)}<small>%</small></b><small>{s.stats.wins||0} 胜 · {s.stats.losses||0} 负</small></article><article><span>估算已实现盈亏</span><b className={(s.stats.realizedPnl||0)>=0?'green':'red'}>{num(s.stats.realizedPnl||0)} <small>USDT</small></b><small>暂未扣除手续费与资金费</small></article><article><span>未实现盈亏</span><b className={(s.stats.unrealizedPnl||0)>=0?'green':'red'}>{num(s.stats.unrealizedPnl||0)} <small>USDT</small></b><small>当前仓位实时估算</small></article><article><span>5m 入场扫描</span><b>{s.stats.scans||0}</b><small>已完成K线触发检查</small></article><article><span>榜单更新</span><b>{s.stats.rankingRefreshes||0}</b><small>成功刷新次数</small></article><article><span>止损上移</span><b>{s.stats.hardStopMoves||0}</b><small>动态保护调整次数</small></article><article className={(s.stats.dataErrors||0)>0?'warning':''}><span>数据异常 / 重试</span><b>{s.stats.dataErrors||0} <small>/ {s.stats.retries||0}</small></b><small>当前通道网络情况</small></article></div><footer className="stats-note">纸面与实盘统计完全隔离；切换下方查看通道不会停止另一套策略。</footer></section>}

export default function Home(){
 const[paper,setPaper]=useState<Snapshot>(()=>empty('paper')),[live,setLive]=useState<Snapshot>(()=>empty('live')),[selected,setSelected]=useState<Channel>('paper');
 const[apiKey,setApiKey]=useState(''),[secret,setSecret]=useState(''),[unlock,setUnlock]=useState(''),[accessPassword,setAccessPassword]=useState(''),[liveAuth,setLiveAuth]=useState<LiveAuth>({configured:false,authenticated:false,expiresAt:null}),[busy,setBusy]=useState(''),[notice,setNotice]=useState('');
 const[params,setParams]=useState<Config>({...DEFAULT_CONFIG});const initialized=useRef(false);
 const snapshots={paper,live},s=snapshots[selected],setSnapshot=(channel:Channel,value:Snapshot)=>(channel==='paper'?setPaper:setLive)(value);
 const call=async(channel:Channel,path:string,body?:unknown)=>{const key=`${channel}:${path}`;setBusy(key);setNotice('');try{const r=await fetch(`/api/${channel}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body??{})});const data=await r.json();if(data.snapshot)setSnapshot(channel,data.snapshot);if(!r.ok){if(channel==='live'&&r.status===401)setLiveAuth(v=>({...v,authenticated:false,expiresAt:null}));throw new Error(data.error||'操作失败')}setNotice(`${channel==='paper'?'纸面':'实盘'}：${data.message||'已完成'}`);return true}catch(e){setNotice(`${channel==='paper'?'纸面':'实盘'}：${e instanceof Error?e.message:'操作失败'}`);return false}finally{setBusy('')}};
 useEffect(()=>{const poll=async()=>{try{const[paperResponse,authResponse]=await Promise.all([fetch('/api/paper/snapshot'),fetch('/api/live/auth/status')]);if(paperResponse.ok){const data=await paperResponse.json();setPaper(data);if(!initialized.current){initialized.current=true;setParams(data.config)}}if(authResponse.ok){const auth=await authResponse.json();setLiveAuth(auth);if(auth.authenticated){const liveResponse=await fetch('/api/live/snapshot');if(liveResponse.ok)setLive(await liveResponse.json());else if(liveResponse.status===401)setLiveAuth({...auth,authenticated:false,expiresAt:null})}else setLive(empty('live'))}}catch{}};poll();const id=setInterval(poll,1000);return()=>clearInterval(id)},[]);
 const connectPaper=()=>call('paper','/connect',{mode:'paper'});
 const connectLive=async()=>{const ok=await call('live','/connect',{mode:'live',apiKey:apiKey.trim(),secretKey:secret.trim(),liveUnlock:unlock});if(ok){setApiKey('');setSecret('');setUnlock('')}};
 const unlockLive=async()=>{setBusy('live:auth');setNotice('');try{const r=await fetch('/api/live/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:accessPassword})});const data=await r.json();if(!r.ok)throw new Error(data.error||'实盘解锁失败');setLiveAuth({configured:true,authenticated:true,expiresAt:data.expiresAt});setAccessPassword('');setSelected('live');const snapshot=await fetch('/api/live/snapshot');if(snapshot.ok)setLive(await snapshot.json());setNotice('实盘控制已解锁')}catch(e){setNotice(e instanceof Error?e.message:'实盘解锁失败')}finally{setBusy('')}};
 const lockLive=async()=>{setBusy('live:logout');try{await fetch('/api/live/auth/logout',{method:'POST'});setLiveAuth(v=>({...v,authenticated:false,expiresAt:null}));setLive(empty('live'));setSelected('paper');setNotice('实盘数据和操作已锁定，实盘策略如已启动仍会继续运行')}finally{setBusy('')}};
 const save=async()=>{if(paper.running||live.running||!liveAuth.authenticated)return;setBusy('config');setNotice('');try{const responses=await Promise.all((['paper','live'] as Channel[]).map(channel=>fetch(`/api/${channel}/config`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params)})));const data=await Promise.all(responses.map(r=>r.json()));if(responses.some(r=>!r.ok))throw new Error(data.find((_,i)=>!responses[i].ok)?.error||'参数同步失败');setPaper(data[0].snapshot);setLive(data[1].snapshot);setNotice('纸面与实盘参数已同步')}catch(e){setNotice(e instanceof Error?e.message:'参数同步失败')}finally{setBusy('')}};
 const active=useMemo(()=>s.ranking.filter(r=>r.directionQualified).length,[s.ranking]);
 const targetRank=useMemo(()=>s.ranking.find(r=>r.eligible&&r.signals['5m']?.above)?.rank??null,[s.ranking]);
 const watchlist=useMemo(()=>s.ranking.flatMap(r=>{const sig=r.signals['5m'];if(!r.eligible||!sig||sig.above||sig.line==null||sig.close==null||!sig.atr||!r.price)return[];const rawGap=sig.line-r.price,gap=Math.max(0,rawGap);return[{...r,gapPrice:rawGap,gapPct:rawGap/r.price*100,gapAtr:gap/sig.atr,trigger:sig.line}]}).sort((a,b)=>a.gapAtr-b.gapAtr||a.rank-b.rank).slice(0,5),[s.ranking]);
 const runningCount=Number(paper.running)+Number(live.running);
 return <main>
  <header><div className="brand"><span>ST</span><div><b>Trend Executor</b><small>BINANCE 双通道自动交易系统</small></div></div><div className="dual-health"><span><i className={paper.running?'pulse':''}/>纸面 {paper.running?'运行中':paper.connected?'待启动':'未连接'}</span><span className="live-health"><i className={live.running?'pulse':''}/>实盘 {!liveAuth.authenticated?'已锁定':live.running?'运行中':live.connected?'待启动':'未连接'}</span></div></header>
  <div className="shell">
   <section className="hero"><div><p className="eyebrow">DUAL ENGINE CONTROL CENTER</p><h1>双轨运行，<em>互不覆盖。</em></h1><p>纸面验证策略 · 实盘独立执行 · 两套仓位、统计与日志完全隔离</p></div><div className="mode-card"><span>并行引擎</span><strong>{runningCount} / 2 运行中</strong><small>纸面与实盘可同时启动</small></div></section>
   {notice&&<div className={`notice ${notice.includes('失败')||notice.includes('错误')||notice.includes('禁止')||notice.includes('停止')?'bad':''}`}>{notice}</div>}
   <section className="channel-grid">
    <article className={`channel-card paper ${selected==='paper'?'selected':''}`}><div className="channel-head"><div><p>PAPER ENGINE</p><h2>纸面交易</h2></div><span className={paper.running?'running':paper.connected?'ok':''}>{paper.running?'运行中':paper.connected?'已连接':'未启用'}</span></div><p className="channel-copy">使用10,000 USDT虚拟资金，独立模拟下单、止损与盈亏。</p><div className="account"><div><span>账户权益</span><b>{num(paper.account?.equity??null)} <small>USDT</small></b></div><div><span>当前仓位</span><b>{paper.position?.symbol||'空仓'}</b></div></div>{!paper.connected&&<button className="primary" disabled={!!busy} onClick={connectPaper}>启用纸面账户</button>}<div className="actions"><button className="start" disabled={!paper.connected||paper.running||!!busy} onClick={()=>call('paper','/start')}>启动纸面策略</button><button disabled={!paper.running||!!busy} onClick={()=>call('paper','/stop')}>停止新开仓</button><button className="danger" disabled={!paper.position||!!busy} onClick={()=>confirm('确认平掉纸面模拟仓位？')&&call('paper','/panic',{confirm:'CLOSE_ALL'})}>平掉纸面仓位</button></div><button className="inspect" onClick={()=>setSelected('paper')}>查看纸面详情</button></article>
    <article className={`channel-card live ${selected==='live'?'selected':''}`}><div className="channel-head"><div><p>LIVE ENGINE</p><h2>Binance 实盘</h2></div><span className={!liveAuth.authenticated?'locked':live.running?'running':live.connected?'ok':''}>{!liveAuth.authenticated?'密码锁定':live.running?'运行中':live.connected?'已连接':'未连接'}</span></div><p className="channel-copy">实盘余额、持仓、日志和所有操作均受访问密码保护；纸面页面保持公开。</p>{!liveAuth.authenticated?<div className="access-lock"><div className="lock-mark">LOCK</div><h3>解锁实盘控制</h3><p>{liveAuth.configured?'输入访问密码后才能查看或操作实盘。会话有效8小时。':'服务器尚未配置访问密码，实盘控制保持关闭。'}</p><label>实盘访问密码<input type="password" value={accessPassword} onChange={e=>setAccessPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&unlockLive()} autoComplete="current-password"/></label><button className="primary live-button" disabled={!!busy||!liveAuth.configured||!accessPassword} onClick={unlockLive}>{busy==='live:auth'?'正在验证…':'解锁实盘控制'}</button></div>:<>{!live.connected?<div className="live-connect"><label>API Key<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="off"/></label><label>Secret Key<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="off"/></label><label>实盘解锁短语<input value={unlock} onChange={e=>setUnlock(e.target.value)} placeholder="我确认实盘风险" autoComplete="off"/></label><button className="primary live-button" disabled={!!busy} onClick={connectLive}>验证并连接实盘</button></div>:<div className="account"><div><span>账户权益</span><b>{num(live.account?.equity??null)} <small>USDT</small></b></div><div><span>当前仓位</span><b>{live.position?.symbol||'空仓'}</b></div></div>}{live.connected&&live.error&&<div className="engine-error"><b>实盘未运行原因</b><span>{live.error}</span></div>}<div className="actions"><button className="start live-start" disabled={!live.connected||live.running||!!busy} onClick={()=>call('live','/start')}>{live.running?'实盘策略运行中':busy==='live:/start'?'正在启动…':'启动实盘策略'}</button><button disabled={!live.running||!!busy} onClick={()=>call('live','/stop')}>停止新开仓</button><button className="danger" disabled={!live.position||!!busy} onClick={()=>confirm('确认市价平掉实盘全部仓位？此操作不可撤销。')&&call('live','/panic',{confirm:'CLOSE_ALL'})}>紧急平仓</button></div><div className="live-session"><span>已安全解锁 · {time(liveAuth.expiresAt)} 到期</span><button onClick={lockLive}>立即锁定</button></div><button className="inspect" onClick={()=>setSelected('live')}>查看实盘详情</button></>}</article>
   </section>
   <section className="params card shared-params"><div className="card-title"><div><p>SHARED RULES</p><h2>两套通道同步策略参数</h2></div><span>ST 10 / 3</span></div><div className="param-grid"><label>趋势线理论风险上限<input type="number" min="1" max="20" step=".5" value={params.maxRiskPct} onChange={e=>setParams({...params,maxRiskPct:+e.target.value})}/><small>% 权益</small></label><label>实时趋势线跌幅上限<input type="number" min="1" max="10" step=".5" value={params.maxTrendDropPct} onChange={e=>setParams({...params,maxTrendDropPct:+e.target.value})}/><small>%</small></label><label>下单保证金缓冲<input type="number" min=".5" max="20" step=".5" value={params.marginReservePct} onChange={e=>setParams({...params,marginReservePct:+e.target.value})}/><small>% 可用余额</small></label><label>榜单数量<input type="number" min="1" max="20" value={params.rankingSize} onChange={e=>setParams({...params,rankingSize:+e.target.value})}/><small>名</small></label><label>榜单刷新<input type="number" min="15" max="300" value={params.rankingRefreshSec} onChange={e=>setParams({...params,rankingRefreshSec:+e.target.value})}/><small>秒</small></label><label>冷却K线<input type="number" min="0" max="20" value={params.cooldownBars} onChange={e=>setParams({...params,cooldownBars:+e.target.value})}/><small>根5m</small></label><label>硬止损保护缓冲<input type="number" min=".5" max="3" step=".1" value={params.hardStopAtr} onChange={e=>setParams({...params,hardStopAtr:+e.target.value})}/><small>ATR</small></label><label>上移阈值<input type="number" min=".1" max="2" step=".1" value={params.hardStopStepAtr} onChange={e=>setParams({...params,hardStopStepAtr:+e.target.value})}/><small>ATR</small></label></div><button className="secondary" disabled={!!busy||paper.running||live.running||!liveAuth.authenticated} onClick={save}>同步保存到纸面与实盘</button><p className="hint">下单基数取账户权益与可用余额较小值，默认预留2%保证金；修改参数前必须停止两套策略并解锁实盘控制。</p></section>
   <nav className="channel-tabs" aria-label="监控通道"><button className={selected==='paper'?'active':''} onClick={()=>setSelected('paper')}><i className={paper.running?'pulse':''}/>纸面详情</button><button className={selected==='live'?'active live-tab':''} onClick={()=>setSelected('live')}><i className={live.running?'pulse':''}/>实盘详情</button><span>当前查看：{selected==='paper'?'纸面交易':'Binance 实盘'} · 不影响另一通道运行</span></nav>
   <StatsView channel={selected} s={s}/>
   <section className="position-pair"><PositionView channel="paper" s={paper}/><PositionView channel="live" s={live}/></section>
   <section className="watch card"><div className="card-title"><div><p>BREAKOUT WATCH · {selected.toUpperCase()}</p><h2>重点观察 · 即将突破</h2></div><span>{watchlist.length} 个候选</span></div>{watchlist.length?<div className="watch-grid">{watchlist.map((r,i)=><article key={r.symbol} className={i===0?'nearest':''}><div className="watch-head"><span>榜单 #{r.rank}</span><b>{i===0?'距离最近':'等待突破'}</b></div><h3>{r.symbol.replace('USDT','')}<small>/USDT</small></h3><div className="watch-prices"><div><span>当前价格</span><strong>{num(r.price,6)}</strong></div><div><span>5m Up Trend线</span><strong>{num(r.trigger,6)}</strong></div></div><div className={`watch-amplitude ${r.gapPct<=0?'crossed':''}`}><span>实时距离幅度</span><b>{r.gapPct>0?`需上涨 ${r.gapPct.toFixed(2)}%`:`盘中已高于线 ${Math.abs(r.gapPct).toFixed(2)}%`}</b></div><div className="distance"><span><i style={{width:`${Math.max(8,100-Math.min(100,r.gapAtr*50))}%`}}/></span><b>{r.gapPct>0?`还差 ${r.gapAtr.toFixed(2)} ATR`:'等待5m收盘确认'}</b></div></article>)}</div>:<div className="empty">当前查看通道没有即将突破的候选币种。</div>}</section>
   <section className="ranking card"><div className="card-title"><div><p>MARKET SCANNER · {selected.toUpperCase()}</p><h2>涨幅榜前 {params.rankingSize}</h2></div><div className="scan-meta"><span>{active} 个高周期合格</span><span>{time(s.lastRankingUpdate)} 更新 · 价格约1秒推送</span></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>合约</th><th>最新价</th><th>24H</th><th>成交额</th>{periods.map(p=><th key={p[0]}>{p[1]}</th>)}<th>5m状态</th><th>① 实时价→趋势线 / 杠杆风险</th><th>② 5m收盘→趋势线</th><th>③ 实时价→保护硬止损</th><th>判断</th></tr></thead><tbody>{s.ranking.length?s.ranking.map(r=>{const line=r.signals['5m']?.line??null,distance=line&&r.price?(r.price-line)/r.price*100:null,status=judgement(r,targetRank,s.position),plan=r.leveragePlan;return <tr key={r.symbol}><td className="rank">{String(r.rank).padStart(2,'0')}</td><td><b>{r.symbol.replace('USDT','')}</b><small>/USDT</small></td><td>{num(r.price,6)}</td><td><span className="gain">+{r.change.toFixed(2)}%</span></td><td>{num(r.quoteVolume/1e6,1)}M</td>{periods.map(p=><td key={p[0]}><span className={`sig ${r.signals[p[0]]?.above?'up':'down'}`}>{r.signals[p[0]]?.above?'上方':'下方'}</span></td>)}<td><span className={`sig ${r.signals['5m']?.above?'up':'down'}`}>{r.signals['5m']?.above?'上方':'下方'}</span></td><td>{r.directionQualified&&distance!=null?<span className={`leverage-plan ${plan.valid?'valid':'invalid'}`}>{plan.valid?`向下 ${distance.toFixed(2)}% · 最终 ${plan.finalLeverage}× · 风险 ${plan.riskPct?.toFixed(2)}%`:distance>=0?`向下 ${distance.toFixed(2)}% · ${plan.reason}`:`需上涨 ${Math.abs(distance).toFixed(2)}%`}</span>:<span className="muted">—</span>}</td><td>{r.directionQualified&&plan.distancePct!=null?<span className={`line-distance ${plan.distancePct>=0?'above':'below'}`}>{plan.distancePct>=0?`向下 ${plan.distancePct.toFixed(2)}%`:`需上涨 ${Math.abs(plan.distancePct).toFixed(2)}%`}</span>:<span className="muted">—</span>}</td><td>{r.directionQualified&&plan.hardStopDistancePct!=null?<span className="line-distance above">保护距离 {plan.hardStopDistancePct.toFixed(2)}%</span>:<span className="muted">—</span>}</td><td><span className={status.signal?'entry-signal':r.rank===targetRank?'eligible':'muted'}>{status.label}</span></td></tr>}):<tr><td colSpan={14}><div className="empty">启用当前通道后加载榜单</div></td></tr>}</tbody></table></div></section>
   <section className="logs card"><div className="card-title"><div><p>SYSTEM EVENTS · {selected.toUpperCase()}</p><h2>{selected==='paper'?'纸面运行日志':'实盘运行日志'}</h2></div><span>最近 {s.logs.length} 条</span></div><div className="log-list">{s.logs.length?s.logs.map((l,i)=><div key={`${l.at}-${i}`}><time>{time(l.at)}</time><span className={l.level}>{l.level.toUpperCase()}</span><p>{l.message}</p></div>):<div className="empty">暂无事件</div>}</div></section>
  </div>
 </main>
}
