import http from 'node:http';
import crypto from 'node:crypto';
import {firstFivePeriodTarget,higherRankRotationTarget,leveragePlan as calculateLeveragePlan,positionNotionalPlan} from './strategy.mjs';

const PORT=Number(process.env.ENGINE_PORT||3001);
const LOCKED_MODE=process.env.ENGINE_MODE||null;
if(LOCKED_MODE&&!['paper','testnet','live'].includes(LOCKED_MODE))throw new Error(`ENGINE_MODE无效：${LOCKED_MODE}`);
const LIVE_ACCESS_PASSWORD=process.env.LIVE_ACCESS_PASSWORD||'';
const LIVE_COOKIE_SECURE=process.env.LIVE_COOKIE_SECURE==='true';
const LIVE_SESSION_TTL_MS=8*60*60*1000;
const LIVE_FAILURE_WINDOW_MS=15*60*1000;
const LIVE_FAILURE_LIMIT=5;
const liveSessions=new Map();
const liveFailures=new Map();
const PROD='https://fapi.binance.com';
const TEST='https://testnet.binancefuture.com';
const MARKET_STREAM='wss://fstream.binance.com/market/ws/!ticker@arr';
const PERIODS=['5m','15m','1h','4h','1d'];
const MARGIN_RETRY_FACTORS=[1,.97,.94,.9,.85,.8];
const config={maxRiskPct:20,maxTrendDropPct:10,marginReservePct:2,rankingSize:10,rankingRefreshSec:60,hardStopAtr:1,hardStopStepAtr:.5,cooldownBars:3};
const state={connected:false,running:false,mode:LOCKED_MODE||'paper',credentials:null,lastTick:null,lastRankingUpdate:null,nextRankingUpdate:null,serverOffset:0,account:null,position:null,ranking:[],logs:[],error:null,last5mCloseTime:null,exchangeInfo:null,exchangeInfoAt:0,cooldowns:new Map(),paperEquity:10000,paperOrders:[],timer:null,busy:false,marketWs:null,marketWsReconnectTimer:null,marketWsRenewTimer:null,marketStream:{status:'disconnected',lastMessage:null,reconnects:0},stats:{engineStartedAt:new Date().toISOString(),runningSince:null,runningMs:0,scans:0,rankingRefreshes:0,retries:0,marginRetries:0,dataErrors:0,entries:0,exits:0,wins:0,losses:0,realizedPnl:0,hardStopMoves:0,rotations:0}};

const iso=()=>new Date().toISOString();
function log(level,message){state.logs.unshift({at:iso(),level,message});state.logs=state.logs.slice(0,120);if(level==='error')state.error=message}
function publicStats(){const runningMs=state.stats.runningMs+(state.stats.runningSince?Date.now()-state.stats.runningSince:0),decided=state.stats.wins+state.stats.losses;return{...state.stats,runningSince:state.stats.runningSince?new Date(state.stats.runningSince).toISOString():null,runningSeconds:Math.floor(runningMs/1000),winRate:decided?state.stats.wins/decided*100:0,unrealizedPnl:state.position?.unrealizedPnl||0}}
function publicState(){return{connected:state.connected,running:state.running,mode:state.mode,lockedMode:LOCKED_MODE,lastTick:state.lastTick,lastRankingUpdate:state.lastRankingUpdate,nextRankingUpdate:state.nextRankingUpdate,account:state.account,position:state.position,ranking:state.ranking.map(row=>({...row,leveragePlan:leveragePlan(row.signals?.['5m'],row.price)})),logs:state.logs,config:{...config},stats:publicStats(),marketStream:{...state.marketStream},error:state.error}}
function startClock(){if(!state.stats.runningSince)state.stats.runningSince=Date.now()}
function stopClock(){if(state.stats.runningSince){state.stats.runningMs+=Date.now()-state.stats.runningSince;state.stats.runningSince=null}}
function base(){return state.mode==='testnet'?TEST:PROD}
function qs(params){return new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=>[k,String(v)])).toString()}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return i<0?[v,'']:[v.slice(0,i),decodeURIComponent(v.slice(i+1))]}))}
function liveSession(req){const token=cookies(req).live_session,expires=token?liveSessions.get(token):null;if(!token||!expires||expires<=Date.now()){if(token)liveSessions.delete(token);return null}return{token,expires}}
function safePasswordMatch(value){const actual=Buffer.from(String(value||'')),expected=Buffer.from(LIVE_ACCESS_PASSWORD);return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)}
function clientKey(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function liveAuthRequired(){return LOCKED_MODE==='live'}
function sessionCookie(token,maxAge){return`live_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Strict; Path=/api/live; Max-Age=${maxAge}${LIVE_COOKIE_SECURE?'; Secure':''}`}
function liveAuthState(req){const session=liveSession(req);return{configured:Boolean(LIVE_ACCESS_PASSWORD),authenticated:Boolean(session),expiresAt:session?new Date(session.expires).toISOString():null}}
function recordLiveFailure(req){const key=clientKey(req),now=Date.now(),existing=liveFailures.get(key);const entry=!existing||existing.startedAt+LIVE_FAILURE_WINDOW_MS<=now?{startedAt:now,count:1}:{...existing,count:existing.count+1};liveFailures.set(key,entry);return entry}
function liveAuthError(message,status=401){const error=new Error(message);error.status=status;return error}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function errorDetail(error){const cause=error?.cause;const code=cause?.code||error?.code;return`${error?.message||'请求失败'}${code?` (${code})`:''}`}
async function request(path,{method='GET',params={},signed=false,baseUrl=base()}={}){
 const p={...params};const headers={};if(signed){if(!state.credentials)throw new Error('尚未配置API凭据');p.timestamp=Date.now()+state.serverOffset;p.recvWindow=5000;const raw=qs(p);p.signature=crypto.createHmac('sha256',state.credentials.secretKey).update(raw).digest('hex');headers['X-MBX-APIKEY']=state.credentials.apiKey}
 const url=`${baseUrl}${path}?${qs(p)}`,maxAttempts=method==='GET'&&!signed?3:1;let lastError;
 for(let attempt=1;attempt<=maxAttempts;attempt++){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(url,{method,headers,signal:ctl.signal});const data=await r.json().catch(()=>({}));if(!r.ok||data.code<0){const e=new Error(data.msg||`Binance HTTP ${r.status}`);e.code=data.code??r.status;e.retryable=r.status>=500;throw e}return data}catch(error){lastError=error;const retryable=error?.retryable||error?.name==='AbortError'||Boolean(error?.cause);if(!retryable||attempt===maxAttempts)break;state.stats.retries++;const wait=attempt===1?400:1000;log('warn',`公开行情请求失败，${wait}ms后进行第${attempt+1}/${maxAttempts}次尝试：${path} · ${errorDetail(error)}`);await sleep(wait)}finally{clearTimeout(timer)}}
 const final=new Error(`${path} 连续${maxAttempts}次失败：${errorDetail(lastError)}`);final.cause=lastError;final.code=lastError?.code;final.status=lastError?.status;final.retryable=lastError?.retryable;throw final
}
async function syncTime(){const t=await request('/fapi/v1/time',{baseUrl:base()});state.serverOffset=Number(t.serverTime)-Date.now()}
function supertrend(candles,length=10,multiplier=3){if(candles.length<length+3)return null;const tr=candles.map((c,i)=>i===0?c.high-c.low:Math.max(c.high-c.low,Math.abs(c.high-candles[i-1].close),Math.abs(c.low-candles[i-1].close))),atr=new Array(candles.length).fill(NaN);atr[length-1]=tr.slice(0,length).reduce((a,b)=>a+b,0)/length;for(let i=length;i<candles.length;i++)atr[i]=(atr[i-1]*(length-1)+tr[i])/length;const upper=new Array(candles.length).fill(NaN),lower=new Array(candles.length).fill(NaN),line=new Array(candles.length).fill(NaN),above=new Array(candles.length).fill(false);let bull=false;for(let i=length-1;i<candles.length;i++){const mid=(candles[i].high+candles[i].low)/2,bu=mid+multiplier*atr[i],bl=mid-multiplier*atr[i];upper[i]=i===length-1||bu<upper[i-1]||candles[i-1].close>upper[i-1]?bu:upper[i-1];lower[i]=i===length-1||bl>lower[i-1]||candles[i-1].close<lower[i-1]?bl:lower[i-1];if(i===length-1)bull=candles[i].close>upper[i];else if(bull&&candles[i].close<lower[i])bull=false;else if(!bull&&candles[i].close>upper[i])bull=true;line[i]=bull?lower[i]:upper[i];above[i]=candles[i].close>line[i]}
 const i=candles.length-1,p=i-1;return{above:above[i],line:line[i],close:candles[i].close,atr:atr[i],closeTime:candles[i].closeTime,previous:{above:above[p],line:line[p],close:candles[p].close,atr:atr[p],closeTime:candles[p].closeTime}}}
async function signal(symbol,interval){try{const raw=await request('/fapi/v1/klines',{params:{symbol,interval,limit:140},baseUrl:PROD});const now=Date.now()+state.serverOffset;const closed=raw.filter(k=>Number(k[6])<now).map(k=>({high:Number(k[2]),low:Number(k[3]),close:Number(k[4]),closeTime:Number(k[6])}));const result=supertrend(closed);if(!result)throw new Error('已完成K线数量不足');return result}catch(error){throw new Error(`${symbol} ${interval}：${errorDetail(error)}`,{cause:error})}}
async function exchangeInfo(){if(state.exchangeInfo&&Date.now()-state.exchangeInfoAt<600000)return state.exchangeInfo;state.exchangeInfo=await request('/fapi/v1/exchangeInfo',{baseUrl:base()});state.exchangeInfoAt=Date.now();return state.exchangeInfo}
function symbolRules(symbol){const s=state.exchangeInfo?.symbols?.find(x=>x.symbol===symbol);if(!s)throw new Error(`${symbol}交易规则不存在`);const lot=s.filters.find(f=>f.filterType==='LOT_SIZE'),marketLot=s.filters.find(f=>f.filterType==='MARKET_LOT_SIZE'),price=s.filters.find(f=>f.filterType==='PRICE_FILTER');return{step:Number(marketLot?.stepSize||lot?.stepSize),minQty:Number(marketLot?.minQty||lot?.minQty),maxQty:Number(marketLot?.maxQty||lot?.maxQty||Infinity),tick:Number(price?.tickSize),status:s.status}}
const decimals=x=>{const s=String(x);return s.includes('e-')?Number(s.split('e-')[1]):(s.split('.')[1]||'').length};
function floorStep(v,step){return Number((Math.floor((v+1e-12)/step)*step).toFixed(decimals(step)))}
function roundTick(v,tick){return Number((Math.round(v/tick)*tick).toFixed(decimals(tick)))}
function leveragePlan(sig,livePrice=sig?.close){return calculateLeveragePlan(sig,livePrice,{maxRiskPct:config.maxRiskPct,maxTrendDropPct:config.maxTrendDropPct,hardStopAtr:config.hardStopAtr})}
function sizingPlan(price,leverage,maxNotionalValue=Infinity,factor=1){const equity=state.account?.equity??state.paperEquity,available=state.account?.available??equity,notional=positionNotionalPlan(equity,available,leverage,maxNotionalValue,config.marginReservePct,factor);return{...notional,qty:notional.targetNotional/price}}
function plannedQuantity(price,leverage,rules,maxNotionalValue=Infinity,factor=1){return floorStep(Math.min(sizingPlan(price,leverage,maxNotionalValue,factor).qty,rules.maxQty),rules.step)}

async function refreshRanking(force=false){if(!force&&state.lastRankingUpdate&&Date.now()-new Date(state.lastRankingUpdate).getTime()<config.rankingRefreshSec*1000)return;const [tickers,productionInfo]=await Promise.all([request('/fapi/v1/ticker/24hr',{baseUrl:PROD}),request('/fapi/v1/exchangeInfo',{baseUrl:PROD})]);const tradingInfo=state.mode==='paper'?productionInfo:await exchangeInfo();state.exchangeInfo=tradingInfo;state.exchangeInfoAt=Date.now();const productionLive=new Set(productionInfo.symbols.filter(s=>s.status==='TRADING'&&s.contractType==='PERPETUAL'&&s.quoteAsset==='USDT').map(s=>s.symbol)),tradingLive=new Set(tradingInfo.symbols.filter(s=>s.status==='TRADING'&&s.contractType==='PERPETUAL'&&s.quoteAsset==='USDT').map(s=>s.symbol));const top=tickers.filter(t=>productionLive.has(t.symbol)).sort((a,b)=>Number(b.priceChangePercent)-Number(a.priceChangePercent)).slice(0,config.rankingSize);const rows=[];for(let i=0;i<top.length;i++){const t=top[i];let sigs={};let reason='方向合格';try{const values=await Promise.all(PERIODS.map(p=>signal(t.symbol,p)));sigs=Object.fromEntries(PERIODS.map((p,n)=>[p,values[n]]));const high=['15m','1h','4h','1d'],failed=high.find(p=>!sigs[p]?.above),directionQualified=!failed,tradable=tradingLive.has(t.symbol);if(!tradable)reason=state.mode==='testnet'?'测试网不可交易':'当前环境不可交易';else if(failed)reason=`${failed}在线下`;rows.push({rank:i+1,symbol:t.symbol,change:Number(t.priceChangePercent),price:Number(t.lastPrice),quoteVolume:Number(t.quoteVolume),signals:sigs,directionQualified,tradable,eligible:tradable&&directionQualified,reason})}catch(e){state.stats.dataErrors++;rows.push({rank:i+1,symbol:t.symbol,change:Number(t.priceChangePercent),price:Number(t.lastPrice),quoteVolume:Number(t.quoteVolume),signals:sigs,directionQualified:false,tradable:false,eligible:false,reason:'数据异常'});log('warn',`${t.symbol}指标读取失败：${e.message}`)}}state.ranking=rows;state.stats.rankingRefreshes++;state.lastRankingUpdate=iso();state.nextRankingUpdate=new Date(Date.now()+config.rankingRefreshSec*1000).toISOString()}
async function refreshPrices(){if(!state.ranking.length)return;const prices=await request('/fapi/v1/ticker/price',{baseUrl:PROD}),bySymbol=new Map(prices.map(item=>[item.symbol,Number(item.price)]));state.ranking=state.ranking.map(row=>bySymbol.has(row.symbol)?{...row,price:bySymbol.get(row.symbol)}:row)}
function startMarketStream(){if(state.marketWs&&(state.marketWs.readyState===WebSocket.OPEN||state.marketWs.readyState===WebSocket.CONNECTING))return;clearTimeout(state.marketWsReconnectTimer);state.marketStream.status='connecting';const ws=new WebSocket(MARKET_STREAM);state.marketWs=ws;ws.addEventListener('open',()=>{state.marketStream.status='connecting';clearTimeout(state.marketWsRenewTimer);state.marketWsRenewTimer=setTimeout(()=>ws.close(1000,'scheduled renewal'),23*60*60*1000+50*60*1000)});ws.addEventListener('message',event=>{try{const payload=JSON.parse(String(event.data));if(!Array.isArray(payload))return;const prices=new Map(payload.map(item=>[item.s,Number(item.c)]).filter(([,price])=>Number.isFinite(price)));if(prices.size)state.ranking=state.ranking.map(row=>prices.has(row.symbol)?{...row,price:prices.get(row.symbol)}:row);if(state.marketStream.status!=='connected')log('info','实时价格流已连接（约1秒更新）');state.marketStream.lastMessage=iso();state.marketStream.status='connected'}catch{}});ws.addEventListener('error',()=>{state.marketStream.status='degraded'});ws.addEventListener('close',()=>{if(state.marketWs!==ws)return;state.marketWs=null;clearTimeout(state.marketWsRenewTimer);state.marketStream.status='reconnecting';state.marketStream.reconnects++;const delay=Math.min(30000,1000*2**Math.min(5,state.marketStream.reconnects-1));state.marketWsReconnectTimer=setTimeout(startMarketStream,delay);log('warn',`实时价格流断开，${Math.round(delay/1000)}秒后重连；期间使用REST兜底`)})}
function stopMarketStream(){clearTimeout(state.marketWsReconnectTimer);clearTimeout(state.marketWsRenewTimer);const ws=state.marketWs;state.marketWs=null;state.marketStream.status='disconnected';if(ws&&(ws.readyState===WebSocket.OPEN||ws.readyState===WebSocket.CONNECTING))ws.close()}

async function syncAccount(){if(state.mode==='paper'){state.account={equity:state.paperEquity+(state.position?.unrealizedPnl||0),available:state.paperEquity};return}
 const account=await request('/fapi/v2/account',{signed:true});const equity=Number(account.totalWalletBalance)+Number(account.totalUnrealizedProfit),available=Number(account.availableBalance);state.account={equity,available};const positions=account.positions.filter(p=>Math.abs(Number(p.positionAmt))>0);if(positions.length>1)throw new Error('检测到多个合约持仓，策略已停止');if(positions.length===1){const p=positions[0];if(Number(p.positionAmt)<0)throw new Error('检测到空头持仓，策略已停止');const previous=state.position,changed=!previous||previous.symbol!==p.symbol,entryPrice=Number(p.entryPrice),rankingPrice=state.ranking.find(row=>row.symbol===p.symbol)?.price,markPrice=[Number(p.markPrice),previous?.markPrice,rankingPrice,entryPrice].find(Number.isFinite);if(changed)state.position={symbol:p.symbol,qty:Number(p.positionAmt),entryPrice,markPrice,unrealizedPnl:Number(p.unrealizedProfit),hardStop:null,hardStopOrderId:null,hardStopOrderKind:null,rank:null};else Object.assign(state.position,{qty:Number(p.positionAmt),entryPrice,markPrice,unrealizedPnl:Number(p.unrealizedProfit)});if(changed||!state.position.hardStopOrderId){const [algoResponse,standardResponse]=await Promise.all([request('/fapi/v1/openAlgoOrders',{signed:true,params:{symbol:p.symbol,algoType:'CONDITIONAL'}}),request('/fapi/v1/openOrders',{signed:true,params:{symbol:p.symbol}})]),algoOrders=Array.isArray(algoResponse)?algoResponse:algoResponse?[algoResponse]:[],standardOrders=Array.isArray(standardResponse)?standardResponse:standardResponse?[standardResponse]:[],algoStops=algoOrders.filter(o=>o.orderType==='STOP_MARKET'&&o.side==='SELL'&&(o.closePosition===true||String(o.closePosition)==='true')).map(o=>({id:o.algoId,kind:'algo',price:Number(o.triggerPrice)})),legacyStops=standardOrders.filter(o=>o.type==='STOP_MARKET'&&o.side==='SELL'&&(o.closePosition===true||String(o.closePosition)==='true')).map(o=>({id:o.orderId,kind:'standard',price:Number(o.stopPrice)})),stops=[...algoStops,...legacyStops];if(stops.length>1)throw new Error(`${p.symbol}存在多个全平硬止损，请先人工核对`);if(stops.length===1){state.position.hardStopOrderId=stops[0].id;state.position.hardStopOrderKind=stops[0].kind;state.position.hardStop=stops[0].price;log('info',`已接管 ${p.symbol} 现有${stops[0].kind==='algo'?'Algo':''}硬止损 ${state.position.hardStop}`)}else log('warn',`${p.symbol}已有持仓但未发现全平硬止损`)}}else if(state.position){log('warn',`${state.position.symbol}交易所持仓已归零`);state.position=null}}
async function ensureOneWay(){if(state.mode==='paper')return;const d=await request('/fapi/v1/positionSide/dual',{signed:true});if(d.dualSidePosition)throw new Error('请先在Binance关闭双向持仓模式，本系统仅支持单向持仓')}
async function leverageBracketCap(symbol,leverage){const response=await request('/fapi/v1/leverageBracket',{signed:true,params:{symbol}}),item=Array.isArray(response)?response.find(row=>row.symbol===symbol):response,eligible=(item?.brackets||[]).filter(bracket=>Number(bracket.initialLeverage)>=leverage),cap=Math.max(0,...eligible.map(bracket=>Number(bracket.notionalCap)||0));return cap}
async function setTradingConfig(symbol,leverage){if(state.mode==='paper')return Infinity;const result=await request('/fapi/v1/leverage',{method:'POST',signed:true,params:{symbol,leverage}});try{await request('/fapi/v1/marginType',{method:'POST',signed:true,params:{symbol,marginType:'CROSSED'}})}catch(e){if(e.code!==-4046)throw e}let maxNotionalValue=Number(result.maxNotionalValue);if(!(maxNotionalValue>0))maxNotionalValue=await leverageBracketCap(symbol,leverage);if(!(maxNotionalValue>0))throw new Error(`${symbol}无法取得${leverage}倍杠杆的交易所名义价值上限`);return maxNotionalValue}
async function marketBuyWithMarginFallback(row,plan,rules,maxNotionalValue){let lastError=null;for(let i=0;i<MARGIN_RETRY_FACTORS.length;i++){const factor=MARGIN_RETRY_FACTORS[i],qty=plannedQuantity(row.price,plan.finalLeverage,rules,maxNotionalValue,factor);if(qty<rules.minQty)break;try{const order=await request('/fapi/v1/order',{method:'POST',signed:true,params:{symbol:row.symbol,side:'BUY',type:'MARKET',quantity:qty,newOrderRespType:'RESULT'}});if(i>0)log('info',`${row.symbol}缩量重试成功，最终数量 ${qty}`);return{order,qty}}catch(e){if(![-2019,-2027].includes(e.code))throw e;lastError=e;if(i===MARGIN_RETRY_FACTORS.length-1)break;state.stats.marginRetries++;const reason=e.code===-2027?'当前杠杆最大仓位超限':'可用保证金不足';log('warn',`${row.symbol}${reason}，确认订单未接受；同步账户后缩量进行第${i+2}/${MARGIN_RETRY_FACTORS.length}次尝试`);await syncAccount();if(state.position)throw new Error(`${row.symbol}缩量前检测到交易所持仓，停止重试以防重复开仓`)}}const final=new Error(`${row.symbol}按可用余额、交易所仓位上限并缩量重试后仍无法开仓`);final.code=lastError?.code;final.cause=lastError;throw final}
async function cancelProtectiveOrder(symbol,id,kind='algo'){if(kind==='standard')return request('/fapi/v1/order',{method:'DELETE',signed:true,params:{symbol,orderId:id}});return request('/fapi/v1/algoOrder',{method:'DELETE',signed:true,params:{algoId:id}})}
async function placeHardStop(symbol,stopPrice,orderIdToCancel=null,orderKindToCancel='algo'){const rules=symbolRules(symbol),rounded=roundTick(stopPrice,rules.tick);if(state.mode==='paper'){state.position.hardStop=rounded;return}
 const order=await request('/fapi/v1/algoOrder',{method:'POST',signed:true,params:{algoType:'CONDITIONAL',symbol,side:'SELL',type:'STOP_MARKET',triggerPrice:rounded,closePosition:'true',workingType:'MARK_PRICE',priceProtect:'true'}}),newAlgoId=order.algoId;if(!newAlgoId)throw new Error(`${symbol} Algo硬止损未返回algoId`);if(orderIdToCancel){try{await cancelProtectiveOrder(symbol,orderIdToCancel,orderKindToCancel)}catch(e){try{await cancelProtectiveOrder(symbol,newAlgoId,'algo')}catch(rollback){log('error',`新旧保护单清理失败，请立即人工核对：${rollback.message}`)}throw new Error(`旧保护单取消失败，已回滚新保护单：${e.message}`)}}state.position.hardStop=rounded;state.position.hardStopOrderId=newAlgoId;state.position.hardStopOrderKind='algo'}
async function enter(row,{skipAccountSync=false,maxNotionalValue=null}={}){const sig=row.signals['5m'];if(!sig?.above||sig.close<=sig.line)return false;const plan=leveragePlan(sig,row.price);if(!plan.valid){log('info',`锁定 #${row.rank} ${row.symbol}，空仓等待：${plan.reason}`);return false}const until=state.cooldowns.get(row.symbol)||0;if(until>sig.closeTime){log('info',`锁定 #${row.rank} ${row.symbol}，等待硬止损冷却结束`);return false}if(!skipAccountSync)await syncAccount();if(state.position)return false;let exchangeMaxNotional=state.mode==='paper'?Infinity:Number(maxNotionalValue);if(state.mode!=='paper'&&!(exchangeMaxNotional>0))exchangeMaxNotional=await setTradingConfig(row.symbol,plan.finalLeverage);const rules=symbolRules(row.symbol);if(rules.status!=='TRADING')throw new Error(`${row.symbol}不可交易`);const initialSizing=sizingPlan(row.price,plan.finalLeverage,exchangeMaxNotional);if(initialSizing.cappedByExchange)log('info',`${row.symbol} ${plan.finalLeverage}倍目标名义价值 ${initialSizing.capitalLimitNotional.toFixed(2)} USDT 超过交易所上限，已压缩至 ${initialSizing.exchangeLimitNotional.toFixed(2)} USDT`);let qty=plannedQuantity(row.price,plan.finalLeverage,rules,exchangeMaxNotional);if(qty<rules.minQty)throw new Error(`${row.symbol}按可用余额及杠杆名义上限计算后，下单数量低于最小值`);let fill=row.price;if(state.mode!=='paper'){const result=await marketBuyWithMarginFallback(row,plan,rules,exchangeMaxNotional);qty=result.qty;fill=Number(result.order.avgPrice)||row.price}const fillPlan=leveragePlan(sig,fill);if(!fillPlan.valid||fillPlan.finalLeverage<plan.finalLeverage){if(state.mode!=='paper')await request('/fapi/v1/order',{method:'POST',signed:true,params:{symbol:row.symbol,side:'SELL',type:'MARKET',quantity:qty,reduceOnly:'true',newOrderRespType:'RESULT'}});log('warn',`${row.symbol}成交后实时风险复核未通过，已立即退出`);return false}
 state.position={symbol:row.symbol,qty,entryPrice:fill,markPrice:row.price,unrealizedPnl:0,hardStop:null,hardStopOrderId:null,hardStopOrderKind:null,rank:row.rank,leverage:fillPlan.finalLeverage,riskLeverage:fillPlan.riskLeverage,distancePct:fillPlan.distancePct,liveLineDistancePct:fillPlan.liveLineDistancePct,hardStopDistancePct:fillPlan.hardStopDistancePct,initialRiskPct:fillPlan.riskPct,entryNotional:qty*fill,exchangeMaxNotional:Number.isFinite(exchangeMaxNotional)?exchangeMaxNotional:null};state.stats.entries++;try{await placeHardStop(row.symbol,fillPlan.hardStop)}catch(e){log('error',`硬止损挂单失败，立即退出：${e.message}`);await closePosition('保护单创建失败');throw e}log('info',`已做多 ${row.symbol}，排名 #${row.rank}，${fillPlan.finalLeverage}倍，实时理论风险 ${fillPlan.riskPct.toFixed(2)}%，名义价值 ${(qty*fill).toFixed(2)} USDT，数量 ${qty}，均价 ${fill}`);return true}
async function cancelHardStop(){if(!state.position?.hardStopOrderId||state.mode==='paper')return;try{await cancelProtectiveOrder(state.position.symbol,state.position.hardStopOrderId,state.position.hardStopOrderKind)}catch(e){if(![-2011,-2013].includes(e.code))log('warn',`保护单取消失败：${e.message}`)}}
async function closePosition(reason){await syncAccount();if(!state.position)return;const p={...state.position};await cancelHardStop();let exitPrice=Number.isFinite(p.markPrice)?p.markPrice:p.entryPrice;if(state.mode==='paper'){const pnl=(exitPrice-p.entryPrice)*p.qty;state.paperEquity+=pnl;state.paperOrders.push({...p,pnl,reason,closedAt:iso()})}else{const order=await request('/fapi/v1/order',{method:'POST',signed:true,params:{symbol:p.symbol,side:'SELL',type:'MARKET',quantity:floorStep(p.qty,symbolRules(p.symbol).step),reduceOnly:'true',newOrderRespType:'RESULT'}}),filledPrice=Number(order.avgPrice);if(Number.isFinite(filledPrice)&&filledPrice>0)exitPrice=filledPrice}const pnl=(exitPrice-p.entryPrice)*p.qty;state.stats.exits++;state.stats.realizedPnl+=pnl;if(pnl>0)state.stats.wins++;else if(pnl<0)state.stats.losses++;state.position=null;log('info',`已退出 ${p.symbol}：${reason}；估算盈亏 ${pnl.toFixed(2)} USDT`)}
async function exitAndRescan(reason){await closePosition(reason);if(state.running&&!state.position){log('info','退出后立即重新扫描首位目标');await scanEntry()}}
async function maybeRotate(){if(!state.running||!state.position)return false;const target=higherRankRotationTarget(state.position,state.ranking);if(!target)return false;const sig=target.signals['5m'],plan=leveragePlan(sig,target.price);if(!plan.valid)return false;const until=state.cooldowns.get(target.symbol)||0;if(until>sig.closeTime)return false;const rules=symbolRules(target.symbol);if(rules.status!=='TRADING')return false;let maxNotionalValue;try{maxNotionalValue=await setTradingConfig(target.symbol,plan.finalLeverage)}catch(e){log('warn',`更高排名目标 #${target.rank} ${target.symbol} 配置失败，继续持有 ${state.position.symbol}：${e.message}`);return false}const exchangeMaximumQty=floorStep(Math.min((maxNotionalValue*(1-config.marginReservePct/100))/target.price,rules.maxQty),rules.step);if(exchangeMaximumQty<rules.minQty)return false;const previous=state.position.symbol;await closePosition(`更高排名目标 #${target.rank} ${target.symbol} 五周期及风险合格，自动换仓`);await syncAccount();if(state.position){log('error',`${previous} 平仓后交易所仍报告持仓，取消换入 ${target.symbol}`);return true}try{const entered=await enter(target,{skipAccountSync:true,maxNotionalValue});if(entered){state.stats.rotations++;log('info',`自动换仓完成：${previous} → #${target.rank} ${target.symbol}`)}else log('warn',`已退出 ${previous}，但更高排名目标 ${target.symbol} 入场复核未通过，保持空仓`)}catch(e){log('error',`已退出 ${previous}，但更高排名目标 ${target.symbol} 入场失败，保持空仓：${e.message}`)}return true}
async function managePosition(){if(!state.position)return;const rank=state.ranking.find(r=>r.symbol===state.position.symbol);if(!rank){await exitAndRescan('跌出涨幅榜前10');return}state.position.rank=rank.rank;state.position.markPrice=rank.price;state.position.unrealizedPnl=(rank.price-state.position.entryPrice)*state.position.qty;const sig=rank.signals['5m']||await signal(rank.symbol,'5m');if(!sig)return;if(state.mode==='paper'&&state.position.hardStop&&rank.price<=state.position.hardStop){state.cooldowns.set(rank.symbol,sig.closeTime+config.cooldownBars*300000);await exitAndRescan('纸面硬止损触发');return}const newClose=sig.closeTime!==state.last5mCloseTime;if(newClose){state.last5mCloseTime=sig.closeTime;if(sig.close<sig.line){await exitAndRescan('5分钟收盘跌破Supertrend');return}}if(await maybeRotate())return;if(newClose){const candidate=sig.line-config.hardStopAtr*sig.atr;if(!state.position.hardStop||candidate-state.position.hardStop>=config.hardStopStepAtr*sig.atr){const old=state.position.hardStopOrderId,oldKind=state.position.hardStopOrderKind;await placeHardStop(rank.symbol,candidate,old,oldKind);state.stats.hardStopMoves++;log('info',`${rank.symbol}硬止损上移至 ${state.position.hardStop}`)}}}
async function scanEntry(){state.stats.scans++;if(state.position)return;const target=firstFivePeriodTarget(state.ranking);if(!target)return;try{await enter(target)}catch(e){log('warn',`锁定目标 #${target.rank} ${target.symbol} 执行失败，保持空仓：${e.message}`)}}
async function tick(){if(state.busy||!state.connected)return;state.busy=true;try{state.lastTick=iso();state.error=null;await syncTime();await refreshRanking();const streamStale=!state.marketStream.lastMessage||Date.now()-new Date(state.marketStream.lastMessage).getTime()>5000;if(streamStale)await refreshPrices();await syncAccount();if(state.position)await managePosition();else if(state.running){const validCloseTimes=state.ranking.map(row=>row.signals?.['5m']?.closeTime).filter(Number.isFinite),newest=validCloseTimes.length?Math.max(...validCloseTimes):null;if(newest&&newest!==state.last5mCloseTime){state.last5mCloseTime=newest;await scanEntry()}}}catch(e){log('error',e.message);if(/多个合约持仓|空头持仓/.test(e.message)){state.running=false;stopClock();log('warn','账户安全检查未通过，已停止新开仓')}}finally{state.busy=false}}
function startLoop(){startMarketStream();if(state.timer)return;state.timer=setInterval(tick,10000);tick()}

async function connect(body){const mode=body.mode;if(!['paper','testnet','live'].includes(mode))throw new Error('运行模式无效');if(LOCKED_MODE&&mode!==LOCKED_MODE)throw new Error(`本引擎已锁定为${LOCKED_MODE==='paper'?'纸面交易':LOCKED_MODE==='live'?'实盘':'测试网'}，禁止切换模式`);if(state.running||state.position)throw new Error('当前通道正在运行或持仓，禁止重新连接');if(mode==='live'&&body.liveUnlock!=='我确认实盘风险')throw new Error('实盘解锁短语不正确');if(mode!=='paper'&&(!body.apiKey||!body.secretKey))throw new Error('请输入API Key和Secret Key');stopClock();state.running=false;state.connected=false;state.mode=mode;state.credentials=mode==='paper'?null:{apiKey:String(body.apiKey),secretKey:String(body.secretKey)};state.position=null;state.exchangeInfo=null;try{if(mode!=='paper'){await syncTime();await ensureOneWay();await syncAccount()}else state.account={equity:state.paperEquity,available:state.paperEquity};state.connected=true}catch(error){state.credentials=null;state.account=null;throw error}log('info',mode==='paper'?'纸面账户已启用':`${mode==='live'?'实盘':'测试网'}账户验证成功`);startLoop();await refreshRanking(true)}
function validateConfig(body){const ranges={maxRiskPct:[1,20],maxTrendDropPct:[1,10],marginReservePct:[.5,20],rankingSize:[1,20],rankingRefreshSec:[15,300],hardStopAtr:[.5,3],hardStopStepAtr:[.1,2],cooldownBars:[0,20]};for(const[k,[min,max]]of Object.entries(ranges)){if(body[k]===undefined)continue;const n=Number(body[k]);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`${k}必须在${min}到${max}之间`);config[k]=n}config.rankingSize=Math.round(config.rankingSize);config.rankingRefreshSec=Math.round(config.rankingRefreshSec);config.cooldownBars=Math.round(config.cooldownBars);state.lastRankingUpdate=null;log('info','策略参数已更新')}

function json(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'http://localhost:3000','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer',...headers});res.end(JSON.stringify(data))}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>100000)throw new Error('请求过大')}return raw?JSON.parse(raw):{}}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,200,{});try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/auth/status'&&req.method==='GET')return json(res,200,liveAuthState(req));if(url.pathname==='/api/auth'&&req.method==='POST'){if(!LIVE_ACCESS_PASSWORD)throw liveAuthError('服务器尚未配置实盘访问密码',503);const key=clientKey(req),failure=liveFailures.get(key),now=Date.now();if(failure&&failure.count>=LIVE_FAILURE_LIMIT&&failure.startedAt+LIVE_FAILURE_WINDOW_MS>now)throw liveAuthError('密码错误次数过多，请15分钟后重试',429);const input=await body(req);if(!safePasswordMatch(input.password)){recordLiveFailure(req);throw liveAuthError('访问密码错误')}liveFailures.delete(key);const token=crypto.randomBytes(32).toString('hex'),expires=now+LIVE_SESSION_TTL_MS;liveSessions.set(token,expires);return json(res,200,{message:'实盘控制已解锁',configured:true,authenticated:true,expiresAt:new Date(expires).toISOString()},{'Set-Cookie':sessionCookie(token,Math.floor(LIVE_SESSION_TTL_MS/1000))})}if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const session=liveSession(req);if(session)liveSessions.delete(session.token);return json(res,200,{message:'实盘控制已锁定'},{'Set-Cookie':sessionCookie('',0)})}if(liveAuthRequired()&&!liveSession(req))throw liveAuthError(LIVE_ACCESS_PASSWORD?'请输入实盘访问密码':'服务器尚未配置实盘访问密码',LIVE_ACCESS_PASSWORD?401:503);if(req.method==='GET'&&url.pathname==='/api/snapshot')return json(res,200,publicState());if(req.method==='POST'&&url.pathname==='/api/connect'){await connect(await body(req));return json(res,200,{message:'连接成功',snapshot:publicState()})}if(req.method==='POST'&&url.pathname==='/api/config'){if(state.running)throw new Error('请先停止策略再修改参数');validateConfig(await body(req));return json(res,200,{message:'参数已保存',snapshot:publicState()})}if(req.method==='POST'&&url.pathname==='/api/start'){if(!state.connected)throw new Error('请先连接账户');if(state.mode==='live'&&!state.credentials)throw new Error('实盘凭据已失效');state.running=true;state.last5mCloseTime=null;startClock();log('info','自动交易已启动');await tick();if(!state.running)throw new Error(state.error||'启动后账户安全检查未通过');return json(res,200,{message:'策略已启动',snapshot:publicState()})}if(req.method==='POST'&&url.pathname==='/api/stop'){state.running=false;stopClock();log('warn','已停止新开仓；现有仓位仍保留硬止损');return json(res,200,{message:'已停止新开仓',snapshot:publicState()})}if(req.method==='POST'&&url.pathname==='/api/panic'){const b=await body(req);if(b.confirm!=='CLOSE_ALL')throw new Error('缺少平仓确认');await closePosition('手动紧急平仓');state.running=false;stopClock();return json(res,200,{message:'紧急平仓完成',snapshot:publicState()})}return json(res,404,{error:'Not found'})}catch(e){if(e.status!==401&&e.status!==429)log('error',e.message);return json(res,e.status||400,{error:e.message,...((e.status===401||e.status===503)?{locked:true}:{}),...(e.status?{}:{snapshot:publicState()})})}});
server.listen(PORT,'127.0.0.1',()=>{const label=state.mode==='paper'?'纸面':state.mode==='live'?'实盘':'测试网';log('info',`${label}交易引擎已启动：http://localhost:${PORT}`);console.log(`Trading engine (${state.mode}): http://localhost:${PORT}`)});
process.on('SIGINT',()=>{state.running=false;stopClock();stopMarketStream();state.credentials=null;liveSessions.clear();server.close(()=>process.exit(0))});
