import http from 'node:http';
import crypto from 'node:crypto';
import {leveragePlan as calculateLeveragePlan} from './strategy.mjs';

const PORT=Number(process.env.ENGINE_PORT||3001);
const PROD='https://fapi.binance.com';
const TEST='https://testnet.binancefuture.com';
const MARKET_STREAM='wss://fstream.binance.com/market/ws/!ticker@arr';
const PERIODS=['5m','15m','1h','4h','1d'];
const config={maxRiskPct:10,rankingSize:10,rankingRefreshSec:60,hardStopAtr:1,hardStopStepAtr:.5,cooldownBars:3};
const state={connected:false,running:false,mode:'paper',credentials:null,lastTick:null,lastRankingUpdate:null,nextRankingUpdate:null,serverOffset:0,account:null,position:null,ranking:[],logs:[],error:null,last5mCloseTime:null,exchangeInfo:null,exchangeInfoAt:0,cooldowns:new Map(),paperEquity:10000,paperOrders:[],timer:null,busy:false,marketWs:null,marketWsReconnectTimer:null,marketWsRenewTimer:null,marketStream:{status:'disconnected',lastMessage:null,reconnects:0},stats:{engineStartedAt:new Date().toISOString(),runningSince:null,runningMs:0,scans:0,rankingRefreshes:0,retries:0,dataErrors:0,entries:0,exits:0,wins:0,losses:0,realizedPnl:0,hardStopMoves:0}};

const iso=()=>new Date().toISOString();
function log(level,message){state.logs.unshift({at:iso(),level,message});state.logs=state.logs.slice(0,120);if(level==='error')state.error=message}
function publicStats(){const runningMs=state.stats.runningMs+(state.stats.runningSince?Date.now()-state.stats.runningSince:0),decided=state.stats.wins+state.stats.losses;return{...state.stats,runningSince:state.stats.runningSince?new Date(state.stats.runningSince).toISOString():null,runningSeconds:Math.floor(runningMs/1000),winRate:decided?state.stats.wins/decided*100:0,unrealizedPnl:state.position?.unrealizedPnl||0}}
function publicState(){return{connected:state.connected,running:state.running,mode:state.mode,lastTick:state.lastTick,lastRankingUpdate:state.lastRankingUpdate,nextRankingUpdate:state.nextRankingUpdate,account:state.account,position:state.position,ranking:state.ranking.map(row=>({...row,leveragePlan:leveragePlan(row.signals?.['5m'])})),logs:state.logs,config:{...config},stats:publicStats(),marketStream:{...state.marketStream},error:state.error}}
function startClock(){if(!state.stats.runningSince)state.stats.runningSince=Date.now()}
function stopClock(){if(state.stats.runningSince){state.stats.runningMs+=Date.now()-state.stats.runningSince;state.stats.runningSince=null}}
function base(){return state.mode==='testnet'?TEST:PROD}
function qs(params){return new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=>[k,String(v)])).toString()}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function errorDetail(error){const cause=error?.cause;const code=cause?.code||error?.code;return`${error?.message||'请求失败'}${code?` (${code})`:''}`}
async function request(path,{method='GET',params={},signed=false,baseUrl=base()}={}){
 const p={...params};const headers={};if(signed){if(!state.credentials)throw new Error('尚未配置API凭据');p.timestamp=Date.now()+state.serverOffset;p.recvWindow=5000;const raw=qs(p);p.signature=crypto.createHmac('sha256',state.credentials.secretKey).update(raw).digest('hex');headers['X-MBX-APIKEY']=state.credentials.apiKey}
 const url=`${baseUrl}${path}?${qs(p)}`,maxAttempts=method==='GET'&&!signed?3:1;let lastError;
 for(let attempt=1;attempt<=maxAttempts;attempt++){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(url,{method,headers,signal:ctl.signal});const data=await r.json().catch(()=>({}));if(!r.ok||data.code<0){const e=new Error(data.msg||`Binance HTTP ${r.status}`);e.code=data.code??r.status;e.retryable=r.status>=500;throw e}return data}catch(error){lastError=error;const retryable=error?.retryable||error?.name==='AbortError'||Boolean(error?.cause);if(!retryable||attempt===maxAttempts)break;state.stats.retries++;const wait=attempt===1?400:1000;log('warn',`公开行情请求失败，${wait}ms后进行第${attempt+1}/${maxAttempts}次尝试：${path} · ${errorDetail(error)}`);await sleep(wait)}finally{clearTimeout(timer)}}
 const final=new Error(`${path} 连续${maxAttempts}次失败：${errorDetail(lastError)}`);final.cause=lastError;throw final
}
async function syncTime(){const t=await request('/fapi/v1/time',{baseUrl:base()});state.serverOffset=Number(t.serverTime)-Date.now()}
function supertrend(candles,length=10,multiplier=3){if(candles.length<length+3)return null;const tr=candles.map((c,i)=>i===0?c.high-c.low:Math.max(c.high-c.low,Math.abs(c.high-candles[i-1].close),Math.abs(c.low-candles[i-1].close))),atr=new Array(candles.length).fill(NaN);atr[length-1]=tr.slice(0,length).reduce((a,b)=>a+b,0)/length;for(let i=length;i<candles.length;i++)atr[i]=(atr[i-1]*(length-1)+tr[i])/length;const upper=new Array(candles.length).fill(NaN),lower=new Array(candles.length).fill(NaN),line=new Array(candles.length).fill(NaN),above=new Array(candles.length).fill(false);let bull=false;for(let i=length-1;i<candles.length;i++){const mid=(candles[i].high+candles[i].low)/2,bu=mid+multiplier*atr[i],bl=mid-multiplier*atr[i];upper[i]=i===length-1||bu<upper[i-1]||candles[i-1].close>upper[i-1]?bu:upper[i-1];lower[i]=i===length-1||bl>lower[i-1]||candles[i-1].close<lower[i-1]?bl:lower[i-1];if(i===length-1)bull=candles[i].close>upper[i];else if(bull&&candles[i].close<lower[i])bull=false;else if(!bull&&candles[i].close>upper[i])bull=true;line[i]=bull?lower[i]:upper[i];above[i]=candles[i].close>line[i]}
 const i=candles.length-1,p=i-1;return{above:above[i],line:line[i],close:candles[i].close,atr:atr[i],closeTime:candles[i].closeTime,previous:{above:above[p],line:line[p],close:candles[p].close,atr:atr[p],closeTime:candles[p].closeTime}}}
async function signal(symbol,interval){try{const raw=await request('/fapi/v1/klines',{params:{symbol,interval,limit:140},baseUrl:PROD});const now=Date.now()+state.serverOffset;const closed=raw.filter(k=>Number(k[6])<now).map(k=>({high:Number(k[2]),low:Number(k[3]),close:Number(k[4]),closeTime:Number(k[6])}));const result=supertrend(closed);if(!result)throw new Error('已完成K线数量不足');return result}catch(error){throw new Error(`${symbol} ${interval}：${errorDetail(error)}`,{cause:error})}}
async function exchangeInfo(){if(state.exchangeInfo&&Date.now()-state.exchangeInfoAt<600000)return state.exchangeInfo;state.exchangeInfo=await request('/fapi/v1/exchangeInfo',{baseUrl:base()});state.exchangeInfoAt=Date.now();return state.exchangeInfo}
function symbolRules(symbol){const s=state.exchangeInfo?.symbols?.find(x=>x.symbol===symbol);if(!s)throw new Error(`${symbol}交易规则不存在`);const lot=s.filters.find(f=>f.filterType==='LOT_SIZE'),marketLot=s.filters.find(f=>f.filterType==='MARKET_LOT_SIZE'),price=s.filters.find(f=>f.filterType==='PRICE_FILTER');return{step:Number(marketLot?.stepSize||lot?.stepSize),minQty:Number(marketLot?.minQty||lot?.minQty),tick:Number(price?.tickSize),status:s.status}}
const decimals=x=>{const s=String(x);return s.includes('e-')?Number(s.split('e-')[1]):(s.split('.')[1]||'').length};
function floorStep(v,step){return Number((Math.floor((v+1e-12)/step)*step).toFixed(decimals(step)))}
function roundTick(v,tick){return Number((Math.round(v/tick)*tick).toFixed(decimals(tick)))}
function leveragePlan(sig){return calculateLeveragePlan(sig,{maxRiskPct:config.maxRiskPct,hardStopAtr:config.hardStopAtr})}

async function refreshRanking(force=false){if(!force&&state.lastRankingUpdate&&Date.now()-new Date(state.lastRankingUpdate).getTime()<config.rankingRefreshSec*1000)return;const [tickers,productionInfo]=await Promise.all([request('/fapi/v1/ticker/24hr',{baseUrl:PROD}),request('/fapi/v1/exchangeInfo',{baseUrl:PROD})]);const tradingInfo=state.mode==='paper'?productionInfo:await exchangeInfo();state.exchangeInfo=tradingInfo;state.exchangeInfoAt=Date.now();const productionLive=new Set(productionInfo.symbols.filter(s=>s.status==='TRADING'&&s.contractType==='PERPETUAL'&&s.quoteAsset==='USDT').map(s=>s.symbol)),tradingLive=new Set(tradingInfo.symbols.filter(s=>s.status==='TRADING'&&s.contractType==='PERPETUAL'&&s.quoteAsset==='USDT').map(s=>s.symbol));const top=tickers.filter(t=>productionLive.has(t.symbol)).sort((a,b)=>Number(b.priceChangePercent)-Number(a.priceChangePercent)).slice(0,config.rankingSize);const rows=[];for(let i=0;i<top.length;i++){const t=top[i];let sigs={};let reason='方向合格';try{const values=await Promise.all(PERIODS.map(p=>signal(t.symbol,p)));sigs=Object.fromEntries(PERIODS.map((p,n)=>[p,values[n]]));const high=['15m','1h','4h','1d'],failed=high.find(p=>!sigs[p]?.above),directionQualified=!failed,tradable=tradingLive.has(t.symbol);if(!tradable)reason=state.mode==='testnet'?'测试网不可交易':'当前环境不可交易';else if(failed)reason=`${failed}在线下`;rows.push({rank:i+1,symbol:t.symbol,change:Number(t.priceChangePercent),price:Number(t.lastPrice),quoteVolume:Number(t.quoteVolume),signals:sigs,directionQualified,tradable,eligible:tradable&&directionQualified,reason})}catch(e){state.stats.dataErrors++;rows.push({rank:i+1,symbol:t.symbol,change:Number(t.priceChangePercent),price:Number(t.lastPrice),quoteVolume:Number(t.quoteVolume),signals:sigs,directionQualified:false,tradable:false,eligible:false,reason:'数据异常'});log('warn',`${t.symbol}指标读取失败：${e.message}`)}}state.ranking=rows;state.stats.rankingRefreshes++;state.lastRankingUpdate=iso();state.nextRankingUpdate=new Date(Date.now()+config.rankingRefreshSec*1000).toISOString()}
async function refreshPrices(){if(!state.ranking.length)return;const prices=await request('/fapi/v1/ticker/price',{baseUrl:PROD}),bySymbol=new Map(prices.map(item=>[item.symbol,Number(item.price)]));state.ranking=state.ranking.map(row=>bySymbol.has(row.symbol)?{...row,price:bySymbol.get(row.symbol)}:row)}
function startMarketStream(){if(state.marketWs&&(state.marketWs.readyState===WebSocket.OPEN||state.marketWs.readyState===WebSocket.CONNECTING))return;clearTimeout(state.marketWsReconnectTimer);state.marketStream.status='connecting';const ws=new WebSocket(MARKET_STREAM);state.marketWs=ws;ws.addEventListener('open',()=>{state.marketStream.status='connecting';clearTimeout(state.marketWsRenewTimer);state.marketWsRenewTimer=setTimeout(()=>ws.close(1000,'scheduled renewal'),23*60*60*1000+50*60*1000)});ws.addEventListener('message',event=>{try{const payload=JSON.parse(String(event.data));if(!Array.isArray(payload))return;const prices=new Map(payload.map(item=>[item.s,Number(item.c)]).filter(([,price])=>Number.isFinite(price)));if(prices.size)state.ranking=state.ranking.map(row=>prices.has(row.symbol)?{...row,price:prices.get(row.symbol)}:row);if(state.marketStream.status!=='connected')log('info','实时价格流已连接（约1秒更新）');state.marketStream.lastMessage=iso();state.marketStream.status='connected'}catch{}});ws.addEventListener('error',()=>{state.marketStream.status='degraded'});ws.addEventListener('close',()=>{if(state.marketWs!==ws)return;state.marketWs=null;clearTimeout(state.marketWsRenewTimer);state.marketStream.status='reconnecting';state.marketStream.reconnects++;const delay=Math.min(30000,1000*2**Math.min(5,state.marketStream.reconnects-1));state.marketWsReconnectTimer=setTimeout(startMarketStream,delay);log('warn',`实时价格流断开，${Math.round(delay/1000)}秒后重连；期间使用REST兜底`)})}
function stopMarketStream(){clearTimeout(state.marketWsReconnectTimer);clearTimeout(state.marketWsRenewTimer);const ws=state.marketWs;state.marketWs=null;state.marketStream.status='disconnected';if(ws&&(ws.readyState===WebSocket.OPEN||ws.readyState===WebSocket.CONNECTING))ws.close()}

async function syncAccount(){if(state.mode==='paper'){state.account={equity:state.paperEquity+(state.position?.unrealizedPnl||0),available:state.paperEquity};return}
 const account=await request('/fapi/v2/account',{signed:true});const equity=Number(account.totalWalletBalance)+Number(account.totalUnrealizedProfit),available=Number(account.availableBalance);state.account={equity,available};const positions=account.positions.filter(p=>Math.abs(Number(p.positionAmt))>0);if(positions.length>1)throw new Error('检测到多个合约持仓，策略已停止');if(positions.length===1){const p=positions[0];if(Number(p.positionAmt)<0)throw new Error('检测到空头持仓，策略已停止');const changed=!state.position||state.position.symbol!==p.symbol;if(changed)state.position={symbol:p.symbol,qty:Number(p.positionAmt),entryPrice:Number(p.entryPrice),markPrice:Number(p.markPrice),unrealizedPnl:Number(p.unrealizedProfit),hardStop:null,hardStopOrderId:null,rank:null};else Object.assign(state.position,{qty:Number(p.positionAmt),entryPrice:Number(p.entryPrice),markPrice:Number(p.markPrice),unrealizedPnl:Number(p.unrealizedProfit)});if(changed||!state.position.hardStopOrderId){const orders=await request('/fapi/v1/openOrders',{signed:true,params:{symbol:p.symbol}});const stops=orders.filter(o=>o.type==='STOP_MARKET'&&o.side==='SELL'&&(o.closePosition===true||String(o.closePosition)==='true'));if(stops.length>1)throw new Error(`${p.symbol}存在多个全平硬止损，请先人工核对`);if(stops.length===1){state.position.hardStopOrderId=stops[0].orderId;state.position.hardStop=Number(stops[0].stopPrice);log('info',`已接管 ${p.symbol} 现有硬止损 ${state.position.hardStop}`)}else log('warn',`${p.symbol}已有持仓但未发现全平硬止损`)}}else if(state.position){log('warn',`${state.position.symbol}交易所持仓已归零`);state.position=null}}
async function ensureOneWay(){if(state.mode==='paper')return;const d=await request('/fapi/v1/positionSide/dual',{signed:true});if(d.dualSidePosition)throw new Error('请先在Binance关闭双向持仓模式，本系统仅支持单向持仓')}
async function setTradingConfig(symbol,leverage){if(state.mode==='paper')return;await request('/fapi/v1/leverage',{method:'POST',signed:true,params:{symbol,leverage}});try{await request('/fapi/v1/marginType',{method:'POST',signed:true,params:{symbol,marginType:'CROSSED'}})}catch(e){if(e.code!==-4046)throw e}}
async function placeHardStop(symbol,stopPrice,orderIdToCancel=null){const rules=symbolRules(symbol),rounded=roundTick(stopPrice,rules.tick);if(state.mode==='paper'){state.position.hardStop=rounded;return}
 const order=await request('/fapi/v1/order',{method:'POST',signed:true,params:{symbol,side:'SELL',type:'STOP_MARKET',stopPrice:rounded,closePosition:'true',workingType:'MARK_PRICE',priceProtect:'TRUE'}});if(orderIdToCancel){try{await request('/fapi/v1/order',{method:'DELETE',signed:true,params:{symbol,orderId:orderIdToCancel}})}catch(e){log('warn',`旧保护单取消失败：${e.message}`)}}state.position.hardStop=rounded;state.position.hardStopOrderId=order.orderId}
async function enter(row){const sig=row.signals['5m'];if(!sig?.above||sig.close<=sig.line)return false;const plan=leveragePlan(sig);if(!plan.valid){log('info',`锁定 #${row.rank} ${row.symbol}，空仓等待：${plan.reason}`);return false}const until=state.cooldowns.get(row.symbol)||0;if(until>sig.closeTime){log('info',`锁定 #${row.rank} ${row.symbol}，等待硬止损冷却结束`);return false}await syncAccount();if(state.position)return false;await setTradingConfig(row.symbol,plan.finalLeverage);const rules=symbolRules(row.symbol);if(rules.status!=='TRADING')throw new Error(`${row.symbol}不可交易`);const equity=state.account?.equity||state.paperEquity,qty=floorStep((equity*plan.finalLeverage)/row.price,rules.step);if(qty<rules.minQty)throw new Error(`${row.symbol}下单数量低于最小值`);let fill=row.price;if(state.mode!=='paper'){const o=await request('/fapi/v1/order',{method:'POST',signed:true,params:{symbol:row.symbol,side:'BUY',type:'MARKET',quantity:qty,newOrderRespType:'RESULT'}});fill=Number(o.avgPrice)||row.price}
 state.position={symbol:row.symbol,qty,entryPrice:fill,markPrice:row.price,unrealizedPnl:0,hardStop:null,hardStopOrderId:null,rank:row.rank,leverage:plan.finalLeverage,baseLeverage:plan.baseLeverage,riskLeverage:plan.riskLeverage,distancePct:plan.distancePct,initialRiskPct:plan.riskPct};state.stats.entries++;try{await placeHardStop(row.symbol,plan.hardStop)}catch(e){log('error',`硬止损挂单失败，立即退出：${e.message}`);await closePosition('保护单创建失败');throw e}log('info',`已做多 ${row.symbol}，排名 #${row.rank}，${plan.finalLeverage}倍，理论风险 ${plan.riskPct.toFixed(2)}%，数量 ${qty}，均价 ${fill}`);return true}
async function cancelHardStop(){if(!state.position?.hardStopOrderId||state.mode==='paper')return;try{await request('/fapi/v1/order',{method:'DELETE',signed:true,params:{symbol:state.position.symbol,orderId:state.position.hardStopOrderId}})}catch(e){if(e.code!==-2011)log('warn',`保护单取消失败：${e.message}`)}}
async function closePosition(reason){await syncAccount();if(!state.position)return;const p={...state.position};await cancelHardStop();let exitPrice=p.markPrice;if(state.mode==='paper'){const pnl=(exitPrice-p.entryPrice)*p.qty;state.paperEquity+=pnl;state.paperOrders.push({...p,pnl,reason,closedAt:iso()})}else{const order=await request('/fapi/v1/order',{method:'POST',signed:true,params:{symbol:p.symbol,side:'SELL',type:'MARKET',quantity:floorStep(p.qty,symbolRules(p.symbol).step),reduceOnly:'true',newOrderRespType:'RESULT'}});exitPrice=Number(order.avgPrice)||exitPrice}const pnl=(exitPrice-p.entryPrice)*p.qty;state.stats.exits++;state.stats.realizedPnl+=pnl;if(pnl>0)state.stats.wins++;else if(pnl<0)state.stats.losses++;state.position=null;log('info',`已退出 ${p.symbol}：${reason}；估算盈亏 ${pnl.toFixed(2)} USDT`)}
async function managePosition(){if(!state.position)return;const rank=state.ranking.find(r=>r.symbol===state.position.symbol);if(!rank){await closePosition('跌出涨幅榜前10');return}state.position.rank=rank.rank;state.position.markPrice=rank.price;state.position.unrealizedPnl=(rank.price-state.position.entryPrice)*state.position.qty;const sig=rank.signals['5m']||await signal(rank.symbol,'5m');if(!sig)return;if(state.mode==='paper'&&state.position.hardStop&&rank.price<=state.position.hardStop){state.cooldowns.set(rank.symbol,sig.closeTime+config.cooldownBars*300000);await closePosition('纸面硬止损触发');return}if(sig.closeTime!==state.last5mCloseTime){state.last5mCloseTime=sig.closeTime;if(sig.close<sig.line){await closePosition('5分钟收盘跌破Supertrend');return}const candidate=sig.line-config.hardStopAtr*sig.atr;if(!state.position.hardStop||candidate-state.position.hardStop>=config.hardStopStepAtr*sig.atr){const old=state.position.hardStopOrderId;await placeHardStop(rank.symbol,candidate,old);state.stats.hardStopMoves++;log('info',`${rank.symbol}硬止损上移至 ${state.position.hardStop}`)}}}
async function scanEntry(){state.stats.scans++;if(state.position)return;const target=state.ranking.find(row=>row.eligible&&row.signals?.['5m']?.above&&row.signals['5m'].close>row.signals['5m'].line);if(!target)return;try{await enter(target)}catch(e){log('warn',`锁定目标 #${target.rank} ${target.symbol} 执行失败，保持空仓：${e.message}`)}}
async function tick(){if(state.busy||!state.connected)return;state.busy=true;try{state.lastTick=iso();state.error=null;await syncTime();await refreshRanking();const streamStale=!state.marketStream.lastMessage||Date.now()-new Date(state.marketStream.lastMessage).getTime()>5000;if(streamStale)await refreshPrices();await syncAccount();if(state.position)await managePosition();else if(state.running){const validCloseTimes=state.ranking.map(row=>row.signals?.['5m']?.closeTime).filter(Number.isFinite),newest=validCloseTimes.length?Math.max(...validCloseTimes):null;if(newest&&newest!==state.last5mCloseTime){state.last5mCloseTime=newest;await scanEntry()}}}catch(e){log('error',e.message);if(/多个合约持仓|空头持仓/.test(e.message))state.running=false}finally{state.busy=false}}
function startLoop(){startMarketStream();if(state.timer)return;state.timer=setInterval(tick,10000);tick()}

async function connect(body){const mode=body.mode;if(!['paper','testnet','live'].includes(mode))throw new Error('运行模式无效');if(mode==='live'&&body.liveUnlock!=='我确认实盘风险')throw new Error('实盘解锁短语不正确');stopClock();state.running=false;state.mode=mode;state.credentials=null;state.position=null;state.exchangeInfo=null;if(mode!=='paper'){if(!body.apiKey||!body.secretKey)throw new Error('请输入API Key和Secret Key');state.credentials={apiKey:String(body.apiKey),secretKey:String(body.secretKey)};await syncTime();await ensureOneWay();await syncAccount()}else{state.account={equity:state.paperEquity,available:state.paperEquity}}state.connected=true;log('info',mode==='paper'?'纸面账户已启用':`${mode==='live'?'实盘':'测试网'}账户验证成功`);startLoop();await refreshRanking(true)}
function validateConfig(body){const ranges={maxRiskPct:[1,10],rankingSize:[1,20],rankingRefreshSec:[15,300],hardStopAtr:[.5,3],hardStopStepAtr:[.1,2],cooldownBars:[0,20]};for(const[k,[min,max]]of Object.entries(ranges)){if(body[k]===undefined)continue;const n=Number(body[k]);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`${k}必须在${min}到${max}之间`);config[k]=n}config.rankingSize=Math.round(config.rankingSize);config.rankingRefreshSec=Math.round(config.rankingRefreshSec);config.cooldownBars=Math.round(config.cooldownBars);state.lastRankingUpdate=null;log('info','策略参数已更新')}

function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'http://localhost:3000','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>100000)throw new Error('请求过大')}return raw?JSON.parse(raw):{}}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,200,{});try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/api/snapshot')return json(res,200,publicState());if(req.method==='POST'&&url.pathname==='/api/connect'){await connect(await body(req));return json(res,200,{message:'连接成功',snapshot:publicState()})}if(req.method==='POST'&&url.pathname==='/api/config'){if(state.running)throw new Error('请先停止策略再修改参数');validateConfig(await body(req));return json(res,200,{message:'参数已保存',snapshot:publicState()})}if(req.method==='POST'&&url.pathname==='/api/start'){if(!state.connected)throw new Error('请先连接账户');if(state.mode==='live'&&!state.credentials)throw new Error('实盘凭据已失效');state.running=true;state.last5mCloseTime=null;startClock();log('info','自动交易已启动');await tick();return json(res,200,{message:'策略已启动',snapshot:publicState()})}if(req.method==='POST'&&url.pathname==='/api/stop'){state.running=false;stopClock();log('warn','已停止新开仓；现有仓位仍保留硬止损');return json(res,200,{message:'已停止新开仓',snapshot:publicState()})}if(req.method==='POST'&&url.pathname==='/api/panic'){const b=await body(req);if(b.confirm!=='CLOSE_ALL')throw new Error('缺少平仓确认');await closePosition('手动紧急平仓');state.running=false;stopClock();return json(res,200,{message:'紧急平仓完成',snapshot:publicState()})}return json(res,404,{error:'Not found'})}catch(e){log('error',e.message);return json(res,400,{error:e.message,snapshot:publicState()})}});
server.listen(PORT,'127.0.0.1',()=>{log('info',`本地交易引擎已启动：http://localhost:${PORT}`);console.log(`Trading engine: http://localhost:${PORT}`)});
process.on('SIGINT',()=>{state.running=false;stopClock();stopMarketStream();state.credentials=null;server.close(()=>process.exit(0))});
